update alunos set aluno_endereco_rua = 'R. Deputado Heitor Alencar Furtado, 1720 ap. 1601' where aluno_id = 	221	;
update alunos set aluno_endereco_rua = 'R. David Carneiro' where aluno_id = 	222	;
update alunos set aluno_endereco_rua = 'R. Sebastião Malucelli, 390 ap. 13 bl. J' where aluno_id = 	223	;
update alunos set aluno_endereco_rua = 'R. Sebastião Malucelli, 390 ap. 13 bl. J' where aluno_id = 	224	;
update alunos set aluno_endereco_rua = 'R. Eugênio Flor, 763' where aluno_id = 	225	;
update alunos set aluno_endereco_rua = 'R. Pará, 1801 ap. 35' where aluno_id = 	226	;
update alunos set aluno_endereco_rua = 'R. Desembargador Motta, 3003' where aluno_id = 	227	;
update alunos set aluno_endereco_rua = 'r. José Cadilhe, 888' where aluno_id = 	228	;
update alunos set aluno_endereco_rua = 'R. Simão Bolivar, 199 ap. 61' where aluno_id = 	229	;
update alunos set aluno_endereco_rua = 'R. Stsaint Hikaire, 480 ap. 23' where aluno_id = 	230	;
update alunos set aluno_endereco_rua = 'R. Homero Camargo de Oliveira, 330' where aluno_id = 	231	;
update alunos set aluno_endereco_rua = 'Av. Visc. Guarapuava, 3165 ap. 207' where aluno_id = 	232	;
update alunos set aluno_endereco_rua = 'R. Amilcare Bientineze, 14' where aluno_id = 	234	;
update alunos set aluno_endereco_rua = '' where aluno_id = 	235	;
update alunos set aluno_endereco_rua = 'R. Camara Júnior, 1422' where aluno_id = 	236	;
update alunos set aluno_endereco_rua = 'R. Piauí, 725 ap. 203' where aluno_id = 	237	;
update alunos set aluno_endereco_rua = 'R. João de Alencar Guimarães, 2645' where aluno_id = 	238	;
update alunos set aluno_endereco_rua = 'R. James Portugal, 233 ap. 21 bl. B4' where aluno_id = 	239	;
update alunos set aluno_endereco_rua = 'Trav. Medianeira, 154' where aluno_id = 	240	;
update alunos set aluno_endereco_rua = 'R. Alexandre Nadolnix, 99 casa-1' where aluno_id = 	241	;
update alunos set aluno_endereco_rua = 'R. Alm. Gonçalves, 1880 ap. 01 Bl. A' where aluno_id = 	243	;
update alunos set aluno_endereco_rua = '7 de abril, 929 ap. 43' where aluno_id = 	244	;
update alunos set aluno_endereco_rua = 'R. Hemero Camargo de Oliveira, 330' where aluno_id = 	245	;
update alunos set aluno_endereco_rua = 'R. Castro Alves, 785 ap. 151' where aluno_id = 	246	;
update alunos set aluno_endereco_rua = 'Av. Sete de Setembro, 3050 ap. 31' where aluno_id = 	247	;
update alunos set aluno_endereco_rua = 'R. Engº Niepce da Silva, 200 - 402' where aluno_id = 	249	;
update alunos set aluno_endereco_rua = 'R. Engº Niepce da Silva, 200 - 402' where aluno_id = 	250	;
update alunos set aluno_endereco_rua = 'R. Edgar de Alencar Guimarães, 300' where aluno_id = 	251	;
update alunos set aluno_endereco_rua = 'R. Alm. Gonçalves, 1880 ap. 01-A' where aluno_id = 	252	;
update alunos set aluno_endereco_rua = 'R. Paraíso do Norte, 270' where aluno_id = 	253	;
update alunos set aluno_endereco_rua = 'Av. Sete de Setembro, 3050 ap. 31' where aluno_id = 	254	;
update alunos set aluno_endereco_rua = 'R. Des. Westphalen, 824 ap. 608-B' where aluno_id = 	255	;
update alunos set aluno_endereco_rua = 'Av. Munhoz da Rocha, 332' where aluno_id = 	256	;
update alunos set aluno_endereco_rua = 'R. Paulo Koloshj, 416' where aluno_id = 	257	;
update alunos set aluno_endereco_rua = 'R. Morretes, 1110 ap. 34' where aluno_id = 	258	;
update alunos set aluno_endereco_rua = 'R. Edgar de Alencar Guimarães, 300' where aluno_id = 	259	;
update alunos set aluno_endereco_rua = 'R. Nunes Machado, 976 ap. 4' where aluno_id = 	260	;
update alunos set aluno_endereco_rua = 'R. Guaianazes' where aluno_id = 	261	;
update alunos set aluno_endereco_rua = 'R. Dom Pedro II, 413 ap. 205' where aluno_id = 	263	;
update alunos set aluno_endereco_rua = 'R. Hipólito da Costa, 1917' where aluno_id = 	264	;
update alunos set aluno_endereco_rua = 'Av. Sete de Setembro, 3146 ap. 1608-B' where aluno_id = 	265	;
update alunos set aluno_endereco_rua = 'R. Morretes, 1110 ap. 34' where aluno_id = 	266	;
update alunos set aluno_endereco_rua = 'Av. Vicente Machado, 452 ap. A-1' where aluno_id = 	267	;
update alunos set aluno_endereco_rua = 'R. Profº Antônio  Tupy Pinheiro, 19' where aluno_id = 	269	;
update alunos set aluno_endereco_rua = 'R. Profº Antônio Tupy Pinheiro, 19' where aluno_id = 	270	;
update alunos set aluno_endereco_rua = 'R. Mons. Manuel Vicente, 565' where aluno_id = 	271	;
update alunos set aluno_endereco_rua = 'R. Ubaldino do Amaral, 1125 ap. 303' where aluno_id = 	272	;
update alunos set aluno_endereco_rua = 'R. Marechal Deodoro, 1115 ap. 502' where aluno_id = 	273	;
update alunos set aluno_endereco_rua = 'R. Chile 1122 Bl 05 ap. 13' where aluno_id = 	274	;
update alunos set aluno_endereco_rua = 'R. Marquês do Paraná, 472' where aluno_id = 	275	;
update alunos set aluno_endereco_rua = 'Mal. Floriano Peixoto, 646-A' where aluno_id = 	276	;
update alunos set aluno_endereco_rua = 'R. Pe. Anchieta, 1576 ap. 61' where aluno_id = 	278	;
update alunos set aluno_endereco_rua = 'Av. Vicente Machado, 452 ap. A-1' where aluno_id = 	279	;
update alunos set aluno_endereco_rua = 'R. João Borsato, 1000' where aluno_id = 	280	;
update alunos set aluno_endereco_rua = 'Av. Visconde de Guarapuava, 5233/ 122' where aluno_id = 	281	;
update alunos set aluno_endereco_rua = 'Av. Affonso Camargo, 4589' where aluno_id = 	282	;
update alunos set aluno_endereco_rua = 'R. João Borsato, 1000' where aluno_id = 	284	;
update alunos set aluno_endereco_rua = 'R. Moysés Marcondes, 920 ap. 42' where aluno_id = 	285	;
update alunos set aluno_endereco_rua = 'Lamenha Lins, 635 ap. 04' where aluno_id = 	286	;
update alunos set aluno_endereco_rua = 'R. José de Alencar, 1055' where aluno_id = 	287	;
update alunos set aluno_endereco_rua = 'r. Maranhão, 2100 ap. 702' where aluno_id = 	288	;
update alunos set aluno_endereco_rua = 'R. Nunes Machado, 976 ap. 21' where aluno_id = 	289	;
update alunos set aluno_endereco_rua = 'Av. Nossa Senhora de Lourdes, 733' where aluno_id = 	290	;
update alunos set aluno_endereco_rua = 'R. Buenos Aires, 658 ap. 602' where aluno_id = 	291	;
update alunos set aluno_endereco_rua = 'Av. Iguaçu, 2141 ap. 62' where aluno_id = 	294	;
update alunos set aluno_endereco_rua = 'Av. Iguaçu, 2141 ap. 62' where aluno_id = 	295	;
update alunos set aluno_endereco_rua = 'Av Silva Jardim, 1856 4º andar' where aluno_id = 	296	;
update alunos set aluno_endereco_rua = 'R. Alexandre Gutierrez, 863' where aluno_id = 	297	;
update alunos set aluno_endereco_rua = 'R. Paraguai, 602' where aluno_id = 	298	;
update alunos set aluno_endereco_rua = 'Alameda Princ. Isabel, 2440' where aluno_id = 	300	;
update alunos set aluno_endereco_rua = 'Al. Princ. Isabel, 2440' where aluno_id = 	301	;
update alunos set aluno_endereco_rua = 'Pça Osório, 205 ap. 503' where aluno_id = 	302	;
update alunos set aluno_endereco_rua = '' where aluno_id = 	303	;
update alunos set aluno_endereco_rua = 'R. Nicolau Maeder, 581 ap. 82' where aluno_id = 	304	;
update alunos set aluno_endereco_rua = 'R. Morretes, 753 ap. 11' where aluno_id = 	306	;
update alunos set aluno_endereco_rua = 'r. Alexandre Gutierrez, 863 ap. 11' where aluno_id = 	307	;
update alunos set aluno_endereco_rua = 'R. Angelo Trevisan, 530  Casa 4' where aluno_id = 	310	;
update alunos set aluno_endereco_rua = 'R. Marquês do Paraná, 472' where aluno_id = 	326	;
update alunos set aluno_endereco_rua = 'Av. Visconde de Guarapuava, 3698' where aluno_id = 	329	;
update alunos set aluno_endereco_rua = 'R. Francisco de Souza Neto, 30' where aluno_id = 	330	;
update alunos set aluno_endereco_rua = 'R. José de Alencar, 1055' where aluno_id = 	331	;
update alunos set aluno_endereco_rua = 'R. Livio Moreira, 880' where aluno_id = 	332	;
update alunos set aluno_endereco_rua = 'Av. Rep. Argentina, 789 ap. 26 C' where aluno_id = 	333	;
update alunos set aluno_endereco_rua = 'R. Paulo Koloshi, 416' where aluno_id = 	334	;
update alunos set aluno_endereco_rua = 'R. Moysés Marcondes, 920 ap. 42' where aluno_id = 	335	;
update alunos set aluno_endereco_rua = 'Av. Visconde de Guarapuava, 3698' where aluno_id = 	336	;
update alunos set aluno_endereco_rua = 'r. Livio Moreira, 880' where aluno_id = 	337	;
update alunos set aluno_endereco_rua = 'R. Fço ader, 840' where aluno_id = 	338	;
update alunos set aluno_endereco_rua = 'Des. Otávio do Amaral, 50 ap. 51' where aluno_id = 	339	;
update alunos set aluno_endereco_rua = 'R. Montese, 261' where aluno_id = 	340	;
update alunos set aluno_endereco_rua = 'R. Fço Ader, 840' where aluno_id = 	341	;
update alunos set aluno_endereco_rua = 'Av. Erasto Gaertner, 1764' where aluno_id = 	342	;
update alunos set aluno_endereco_rua = 'r. Paraíso do Norte, 270 Pinhais - Pr' where aluno_id = 	343	;
update alunos set aluno_endereco_rua = 'r. Purus, 34' where aluno_id = 	344	;
update alunos set aluno_endereco_rua = 'r. Morretes, 753 ap. 4' where aluno_id = 	345	;
update alunos set aluno_endereco_rua = 'Av. Visconde de Guarapuava, 3165 ap. 207' where aluno_id = 	346	;
update alunos set aluno_endereco_rua = 'R. Prof. Paulo D  Assumpção, 132' where aluno_id = 	347	;
update alunos set aluno_endereco_rua = 'R. Tem. Brig. Francisco A C Mello, 528' where aluno_id = 	348	;
update alunos set aluno_endereco_rua = 'r. Ten Brig.Francisco A C Mello, 528' where aluno_id = 	349	;
update alunos set aluno_endereco_rua = 'R. Ten Brig. Francisco A C Mello, 528' where aluno_id = 	350	;
update alunos set aluno_endereco_rua = 'r. Prof. Paulo D Assumpçao, 132' where aluno_id = 	351	;
update alunos set aluno_endereco_rua = 'Av. Visconde de Guarapuava, 3698' where aluno_id = 	353	;
update alunos set aluno_endereco_rua = 'R. Padre Anchieta, 1576 ap. 61' where aluno_id = 	354	;
update alunos set aluno_endereco_rua = 'R. Antonio Gruba, 15' where aluno_id = 	355	;
update alunos set aluno_endereco_rua = 'R. comendador C. Jr., 260' where aluno_id = 	356	;
update alunos set aluno_endereco_rua = 'Av. Iguaçu, 2141 ap. 62' where aluno_id = 	357	;
update alunos set aluno_endereco_rua = 'R. Padre Agostinho, 1615' where aluno_id = 	358	;
update alunos set aluno_endereco_rua = 'R. Francisco de Souza Neto, 90' where aluno_id = 	360	;
update alunos set aluno_endereco_rua = 'R. Ouro Verde, 514' where aluno_id = 	361	;
update alunos set aluno_endereco_rua = 'R. Raul Joaquim Quadro Neves, 57 ap. 211' where aluno_id = 	362	;
update alunos set aluno_endereco_rua = 'R. Prof. Sebastião Paraná, 445 ap. 22 A' where aluno_id = 	363	;
update alunos set aluno_endereco_rua = 'R. Hassib Jezzini, 537' where aluno_id = 	364	;
update alunos set aluno_endereco_rua = 'R. Pasteur, 260 ap. 1202' where aluno_id = 	365	;
update alunos set aluno_endereco_rua = 'TV. Frei Caneca, 105/ 21' where aluno_id = 	366	;
update alunos set aluno_endereco_rua = 'R. Frederico Maurer, 1646' where aluno_id = 	367	;
update alunos set aluno_endereco_rua = 'R. Visconde de Abaeté, 183 Casa 2' where aluno_id = 	368	;
update alunos set aluno_endereco_rua = 'Av. João Gualberto, 1134 ap. 82' where aluno_id = 	369	;
update alunos set aluno_endereco_rua = 'R. Lamenha Lins, 1110 ap. 31 B' where aluno_id = 	370	;
update alunos set aluno_endereco_rua = 'Av. João Gualberto, 1134 ap. 82' where aluno_id = 	371	;
update alunos set aluno_endereco_rua = 'R. Guilherme Pugsley, 1235' where aluno_id = 	372	;
update alunos set aluno_endereco_rua = 'R. Heitor de Andrade, 155' where aluno_id = 	373	;
update alunos set aluno_endereco_rua = 'Av. Cândido de Abreu, 180/ 102' where aluno_id = 	374	;
update alunos set aluno_endereco_rua = 'R. Prudente de Morais, 124' where aluno_id = 	375	;
update alunos set aluno_endereco_rua = 'Av. Visconde de Guarapuava, 4125' where aluno_id = 	376	;
update alunos set aluno_endereco_rua = 'Raul Joaquim Quadro Gomes, 57 ap. 211' where aluno_id = 	377	;
update alunos set aluno_endereco_rua = 'R. Guilherme Pugsley, 2286 ap. 114 Bl. B' where aluno_id = 	378	;
update alunos set aluno_endereco_rua = 'R. Guilherme Pugsley, 2286 Bl. B ap. 14' where aluno_id = 	379	;
update alunos set aluno_endereco_rua = 'R. Maranhão, 2100 ap. 702' where aluno_id = 	380	;
update alunos set aluno_endereco_rua = 'R. Francisco de Souza Neto, 30' where aluno_id = 	381	;
update alunos set aluno_endereco_rua = 'R. Roberto Lobo, 58' where aluno_id = 	382	;
update alunos set aluno_endereco_rua = 'Praça Osório, 205 ap. 503' where aluno_id = 	383	;
update alunos set aluno_endereco_rua = 'Av. João Gualberto, 1134 ap. 82' where aluno_id = 	384	;
update alunos set aluno_endereco_rua = 'R. Engenheiro Rebouças, 2895 ap. 43' where aluno_id = 	385	;
update alunos set aluno_endereco_rua = 'R. Padre Anchieta, 1576 ap. 61' where aluno_id = 	386	;
update alunos set aluno_endereco_rua = 'Av. Visconde de Guarapuava, 4125' where aluno_id = 	388	;
update alunos set aluno_endereco_rua = 'R. Heitor de andrade, 155' where aluno_id = 	389	;
update alunos set aluno_endereco_rua = 'R. José Cadilhe, 888' where aluno_id = 	391	;
update alunos set aluno_endereco_rua = 'R. Paraguai, 602' where aluno_id = 	392	;
update alunos set aluno_endereco_rua = 'Clementino do Pic., 130' where aluno_id = 	393	;
update alunos set aluno_endereco_rua = 'R. Roberto Lobom 58' where aluno_id = 	394	;
update alunos set aluno_endereco_rua = 'R. Hassib Jezzini, 537' where aluno_id = 	396	;
update alunos set aluno_endereco_rua = 'R. José Palée - Conj. Roma, 285 ap. 42 Bl. H' where aluno_id = 	397	;
update alunos set aluno_endereco_rua = 'R. Pasteur, 443 ap. 1502' where aluno_id = 	398	;
update alunos set aluno_endereco_rua = 'R. Almirante Gonçalves, 1880 ap. 01' where aluno_id = 	399	;
update alunos set aluno_endereco_rua = 'R. Pedro Krasinski, 166 ap. 31A' where aluno_id = 	400	;
update alunos set aluno_endereco_rua = 'R. Capiberibe, 835' where aluno_id = 	401	;
update alunos set aluno_endereco_rua = 'R. Eugenio Parolin, 138' where aluno_id = 	402	;
update alunos set aluno_endereco_rua = 'r. Lamenha Lins, 2178' where aluno_id = 	403	;
update alunos set aluno_endereco_rua = 'R. Capiberibe, 835' where aluno_id = 	404	;
update alunos set aluno_endereco_rua = 'Travessa Lange, 115 ap. 62' where aluno_id = 	405	;
update alunos set aluno_endereco_rua = 'R. Hassib Jezzini, 537' where aluno_id = 	407	;
update alunos set aluno_endereco_rua = 'R. Frederico Maurer, 1646' where aluno_id = 	408	;
update alunos set aluno_endereco_rua = 'R. Pasteur, 260' where aluno_id = 	409	;
update alunos set aluno_endereco_rua = 'R. Lisimaco Ferreira Costa, 225 ap. 92' where aluno_id = 	410	;
update alunos set aluno_endereco_rua = 'R. Lisimaco Ferreira Costa, 225 ap. 92' where aluno_id = 	411	;
update alunos set aluno_endereco_rua = 'R. Alberto Stenzowski, 110 ap. 116' where aluno_id = 	412	;
update alunos set aluno_endereco_rua = 'R. Tenente Francisco de Souza, 1631' where aluno_id = 	414	;
update alunos set aluno_endereco_rua = 'R. Pastor Carlos Frank, 87' where aluno_id = 	415	;
update alunos set aluno_endereco_rua = 'R. Bento Viana, 932 ap. 192' where aluno_id = 	416	;
update alunos set aluno_endereco_rua = 'R. Bento Viana, 932 ap. 192' where aluno_id = 	417	;
update alunos set aluno_endereco_rua = 'R. Buenos Aires, 658 ap. 702' where aluno_id = 	418	;
update alunos set aluno_endereco_rua = 'R. Buenos Aires, 658 ap. 702' where aluno_id = 	419	;
update alunos set aluno_endereco_rua = 'r. Pastor Carlos Frank, 87' where aluno_id = 	420	;
update alunos set aluno_endereco_rua = 'Lamenhas Lins, 1110 ap. 5317' where aluno_id = 	421	;
update alunos set aluno_endereco_rua = 'R. Palmeiras, 18 ap. 202' where aluno_id = 	422	;
update alunos set aluno_endereco_rua = 'R. Eugenio José de Souza, 1490 ap. 31 Bl. 05' where aluno_id = 	424	;
update alunos set aluno_endereco_rua = 'R. Pastor Carlos Frank, 87' where aluno_id = 	425	;
update alunos set aluno_endereco_rua = 'Osório Samas de Oliveira, 07' where aluno_id = 	426	;
update alunos set aluno_endereco_rua = 'R. Maestro Francisco Antonelo, 2222' where aluno_id = 	427	;
update alunos set aluno_endereco_rua = 'R. Pastor Carlos Frank, 87' where aluno_id = 	428	;
update alunos set aluno_endereco_rua = 'R. Homero Camargo de Oliveira' where aluno_id = 	429	;
update alunos set aluno_endereco_rua = 'R. Adelino Leal Nunes, 108' where aluno_id = 	430	;
update alunos set aluno_endereco_rua = 'r. João Alencar Guimarães, 981' where aluno_id = 	431	;
update alunos set aluno_endereco_rua = 'R. francisco Ader, 840' where aluno_id = 	433	;
update alunos set aluno_endereco_rua = 'R. Oyapok, 70' where aluno_id = 	435	;
update alunos set aluno_endereco_rua = 'R. Silva Jardim' where aluno_id = 	436	;
update alunos set aluno_endereco_rua = 'R. Guilhermina Pugsley, 706 ap. 1402' where aluno_id = 	437	;
update alunos set aluno_endereco_rua = 'R. Moysés Marcondes, 920 ap. 42' where aluno_id = 	438	;
update alunos set aluno_endereco_rua = 'R. Oyapoki, 70' where aluno_id = 	439	;
update alunos set aluno_endereco_rua = 'R. Capiberibe, 835' where aluno_id = 	441	;
update alunos set aluno_endereco_rua = 'R. Rodolpho Senfy, 900' where aluno_id = 	442	;
update alunos set aluno_endereco_rua = 'R. Joaquim Silveira da Motta, 170 - casa 2' where aluno_id = 	443	;
update alunos set aluno_endereco_rua = 'R. Rodolpho Sonff, 900' where aluno_id = 	444	;
update alunos set aluno_endereco_rua = 'r. José Cadielo, 888' where aluno_id = 	445	;
update alunos set aluno_endereco_rua = 'R. Engenheiros Rebouças, 2895 ap. 43' where aluno_id = 	446	;
update alunos set aluno_endereco_rua = 'R. Rodolpho Senff, 900' where aluno_id = 	447	;
update alunos set aluno_endereco_rua = 'r. Prudente de Morais, 1291' where aluno_id = 	448	;
update alunos set aluno_endereco_rua = 'Av. Iguaçu, 2020 ap. 320' where aluno_id = 	449	;
update alunos set aluno_endereco_rua = 'Av. Iguaçu, 2020 ap. 320' where aluno_id = 	450	;
update alunos set aluno_endereco_rua = 'João Hauro, 191' where aluno_id = 	452	;
update alunos set aluno_endereco_rua = 'R. Uniflor, 549/933' where aluno_id = 	453	;
update alunos set aluno_endereco_rua = 'R. Uniflor, 933 / 549' where aluno_id = 	454	;
update alunos set aluno_endereco_rua = 'Av. Paraná, 2226' where aluno_id = 	455	;
update alunos set aluno_endereco_rua = 'Av. Rep. Argentina, 789 ap. 26 C' where aluno_id = 	456	;
update alunos set aluno_endereco_rua = 'R. Joaquim Silveira da Mota, 170 Casa 2' where aluno_id = 	458	;
update alunos set aluno_endereco_rua = 'R. Herculano de Souza, 320' where aluno_id = 	459	;
update alunos set aluno_endereco_rua = 'Av. Manoel Ribas, 6354' where aluno_id = 	460	;
update alunos set aluno_endereco_rua = 'R. Flávio Dallegrave, 23' where aluno_id = 	461	;
update alunos set aluno_endereco_rua = 'R. Ary Barroso, 664' where aluno_id = 	462	;
update alunos set aluno_endereco_rua = 'Profª Ivete F. de Figueira, 20' where aluno_id = 	464	;
update alunos set aluno_endereco_rua = 'R. 24 de maio, 1450 ap. 06' where aluno_id = 	465	;
update alunos set aluno_endereco_rua = 'Travessa Lange, 115 ap. 62' where aluno_id = 	466	;
update alunos set aluno_endereco_rua = 'R. Flávio Dallegrave, 23' where aluno_id = 	467	;
update alunos set aluno_endereco_rua = 'R. Bispo Dom José, 2231 ap. 32' where aluno_id = 	468	;
update alunos set aluno_endereco_rua = 'R. Capiberibe, 411' where aluno_id = 	470	;
update alunos set aluno_endereco_rua = 'Dez. Costa Carvalho, 435' where aluno_id = 	471	;
update alunos set aluno_endereco_rua = 'r. Ruperto Felisc, 97' where aluno_id = 	472	;
update alunos set aluno_endereco_rua = 'R. Comendador Fontana, 405 ap. 803' where aluno_id = 	473	;
update alunos set aluno_endereco_rua = 'Praça Itália, 21' where aluno_id = 	474	;
update alunos set aluno_endereco_rua = 'Av. Iguaçu, 2020 ap. 320' where aluno_id = 	475	;
update alunos set aluno_endereco_rua = 'Praça Itália, 21' where aluno_id = 	476	;
update alunos set aluno_endereco_rua = 'Rodovia dos Minerios, 88' where aluno_id = 	477	;
update alunos set aluno_endereco_rua = 'R. Almirante Tamandaré, 597 ap. 201 ed. Topazio' where aluno_id = 	478	;
update alunos set aluno_endereco_rua = 'R. Carneiro Lobo, 649' where aluno_id = 	479	;
update alunos set aluno_endereco_rua = 'R. Lamenha Lins, 260 ap. 401' where aluno_id = 	480	;
update alunos set aluno_endereco_rua = 'R. Cel. Dulcidio, 1454 ap. 4' where aluno_id = 	481	;
update alunos set aluno_endereco_rua = 'R. Profº Maestro R. Suriane, 90' where aluno_id = 	482	;
update alunos set aluno_endereco_rua = 'R. Profº Maestro R. Suriane, 90' where aluno_id = 	483	;
update alunos set aluno_endereco_rua = 'R. Comendador Araujo, 193 ap. 10 A' where aluno_id = 	484	;
update alunos set aluno_endereco_rua = 'R. Petit Carneiro, 633 ap. 22' where aluno_id = 	485	;
update alunos set aluno_endereco_rua = 'R. Maria Fatuchj, 82' where aluno_id = 	486	;
update alunos set aluno_endereco_rua = 'R. Marcelino Champagnat, 760' where aluno_id = 	487	;
update alunos set aluno_endereco_rua = 'Av. Nossa Srª Aparecida, 501 ap. 1131' where aluno_id = 	488	;
update alunos set aluno_endereco_rua = 'R. Frei Orlando, 833' where aluno_id = 	490	;
update alunos set aluno_endereco_rua = 'R. Frei Orlando, 833' where aluno_id = 	491	;
update alunos set aluno_endereco_rua = 'R. Ladislau Snak, 72' where aluno_id = 	492	;
update alunos set aluno_endereco_rua = 'João Carlos de Souza Castro, 277' where aluno_id = 	493	;
update alunos set aluno_endereco_rua = 'Al. Júlia da Costa, 353' where aluno_id = 	494	;
update alunos set aluno_endereco_rua = 'Av. Visconde de Guarapuava, 3630' where aluno_id = 	495	;
update alunos set aluno_endereco_rua = 'Al. Prudente de Moraes, 1241' where aluno_id = 	496	;
update alunos set aluno_endereco_rua = 'R. Simão Bolivar, 15 ap. 43' where aluno_id = 	497	;
update alunos set aluno_endereco_rua = 'R. Simão Bolivar, 15 ap. 43' where aluno_id = 	498	;
update alunos set aluno_endereco_rua = 'R. Petit Carneiro, 633 ap. 22' where aluno_id = 	499	;
update alunos set aluno_endereco_rua = 'R. Petit Carneiro, 633 ap. 22' where aluno_id = 	500	;
update alunos set aluno_endereco_rua = 'R. Cel. Dulcidio, 1454 ap. 4' where aluno_id = 	501	;
update alunos set aluno_endereco_rua = 'R. Angelo Sampaio, 1157' where aluno_id = 	502	;
update alunos set aluno_endereco_rua = 'Av. Argentina, 85' where aluno_id = 	504	;
update alunos set aluno_endereco_rua = 'Emiliano Perneta, 640' where aluno_id = 	505	;
update alunos set aluno_endereco_rua = 'R. Maranhão, 2100 ap. 702' where aluno_id = 	507	;
update alunos set aluno_endereco_rua = 'R. Lamenha Lins, 2178' where aluno_id = 	508	;
update alunos set aluno_endereco_rua = 'R. Lamenha Lins, 1754 ap. 24' where aluno_id = 	509	;
update alunos set aluno_endereco_rua = 'R. Otacílio Granzotto, 291 - Campo Belo do Sul -SC' where aluno_id = 	510	;
update alunos set aluno_endereco_rua = 'Heitor de Andrade, 155' where aluno_id = 	511	;
update alunos set aluno_endereco_rua = 'R. Bueno Aires, 486 ap. 102' where aluno_id = 	513	;
update alunos set aluno_endereco_rua = 'R. Maria Fatuch, 82' where aluno_id = 	514	;
update alunos set aluno_endereco_rua = 'Sete de Abril, 929 ap. 43' where aluno_id = 	515	;
update alunos set aluno_endereco_rua = 'Estrada Graciosa, 6' where aluno_id = 	516	;
update alunos set aluno_endereco_rua = 'R. Dr. Raul Carneiro Filho' where aluno_id = 	517	;
update alunos set aluno_endereco_rua = 'R. Francisco Torres, 110 ap. 1' where aluno_id = 	519	;
update alunos set aluno_endereco_rua = 'R. Eugênio Parolin, 138' where aluno_id = 	520	;
update alunos set aluno_endereco_rua = 'Zildo Manoel da Cruz, 30' where aluno_id = 	521	;
update alunos set aluno_endereco_rua = 'R. Fco Rocha, 1750 ap. 806' where aluno_id = 	522	;
update alunos set aluno_endereco_rua = 'R. Pastor Carlos Frank, 307' where aluno_id = 	524	;
update alunos set aluno_endereco_rua = 'R. Pastor Carlos Frank, 307' where aluno_id = 	525	;
update alunos set aluno_endereco_rua = 'R. Raggi Izar, 2108' where aluno_id = 	527	;
update alunos set aluno_endereco_rua = 'R. Raggi Izar, 2108' where aluno_id = 	528	;
update alunos set aluno_endereco_rua = 'R. Frederico Maurer, 245' where aluno_id = 	529	;
update alunos set aluno_endereco_rua = 'R. Pastor Carlos Frank, 307' where aluno_id = 	530	;
update alunos set aluno_endereco_rua = 'R. Saint Hilaire Ap. 483 - ap. 258' where aluno_id = 	532	;
update alunos set aluno_endereco_rua = 'R. Dr. Antônio Amarante, 331' where aluno_id = 	533	;
update alunos set aluno_endereco_rua = 'Engº Niepce da Silva, 200 ap. 101 bl. 10' where aluno_id = 	535	;
update alunos set aluno_endereco_rua = 'R. Canadá, 2208 ap. 23 bl. A-6' where aluno_id = 	536	;
update alunos set aluno_endereco_rua = 'R. Francisco Torres, 110 ap. 1' where aluno_id = 	537	;
update alunos set aluno_endereco_rua = 'R. Esanisto Berlize, 96' where aluno_id = 	538	;
update alunos set aluno_endereco_rua = 'r. Evaristo Berlize, 96' where aluno_id = 	539	;
update alunos set aluno_endereco_rua = 'R. Heitor de Andrade, 614' where aluno_id = 	541	;
update alunos set aluno_endereco_rua = 'R. Joinvile, 2939' where aluno_id = 	542	;
update alunos set aluno_endereco_rua = 'R. Dr. Raul Carneiro Filho, 229' where aluno_id = 	543	;
update alunos set aluno_endereco_rua = 'r. Antônio Pacce, 127' where aluno_id = 	544	;
update alunos set aluno_endereco_rua = 'R. Antônio Pacce, 127' where aluno_id = 	545	;
update alunos set aluno_endereco_rua = 'r. Nunes Machado, 257' where aluno_id = 	546	;
update alunos set aluno_endereco_rua = 'Murilo do Amaral Ferreira, 570' where aluno_id = 	547	;
update alunos set aluno_endereco_rua = 'R. Canadá, 2248 bl. B5 ap. 21' where aluno_id = 	548	;
update alunos set aluno_endereco_rua = 'Pça Itália, 21' where aluno_id = 	549	;
update alunos set aluno_endereco_rua = 'R. Murilo do Amaral Ferreira, 570' where aluno_id = 	550	;
update alunos set aluno_endereco_rua = 'r. Canadá, 2248 ap. 21 bl. B5' where aluno_id = 	551	;
update alunos set aluno_endereco_rua = 'Av. Argentina, 85' where aluno_id = 	552	;
update alunos set aluno_endereco_rua = 'R. Curupis, 210' where aluno_id = 	554	;
update alunos set aluno_endereco_rua = 'R. Paulina Ader, 418' where aluno_id = 	555	;
update alunos set aluno_endereco_rua = 'R. Antônio Pacce, 127' where aluno_id = 	556	;
update alunos set aluno_endereco_rua = 'Frei Orlando, 1410' where aluno_id = 	557	;
update alunos set aluno_endereco_rua = 'Av. Irai, 1200' where aluno_id = 	558	;
update alunos set aluno_endereco_rua = 'Av. Irai, 1200' where aluno_id = 	559	;
update alunos set aluno_endereco_rua = 'Av. Irai, 1200' where aluno_id = 	560	;
update alunos set aluno_endereco_rua = 'R. D. Pedro I, 409 ap. 31' where aluno_id = 	561	;
update alunos set aluno_endereco_rua = 'R. Eng. Rebouças, 2429' where aluno_id = 	562	;
update alunos set aluno_endereco_rua = 'R. Eng. Rebouças, 2429' where aluno_id = 	563	;
update alunos set aluno_endereco_rua = 'R. 24 de Maio, 420' where aluno_id = 	564	;
update alunos set aluno_endereco_rua = 'Av. Argentina, 85' where aluno_id = 	565	;
update alunos set aluno_endereco_rua = 'R. João Itiberê, 4' where aluno_id = 	566	;
update alunos set aluno_endereco_rua = 'R. D. Pedro I, 409' where aluno_id = 	567	;
update alunos set aluno_endereco_rua = 'R. Bruno Filgueira, 2100 ap. 131' where aluno_id = 	568	;
update alunos set aluno_endereco_rua = 'R. Dom Orione, 280' where aluno_id = 	569	;
update alunos set aluno_endereco_rua = 'R. Petit Carneiro, 1027 ap. 81' where aluno_id = 	570	;
update alunos set aluno_endereco_rua = 'R. Canadá, 2208 ap. 23 bl. A-6' where aluno_id = 	571	;
update alunos set aluno_endereco_rua = 'R. Lamenha Lins, 2178 ap. 34' where aluno_id = 	572	;
update alunos set aluno_endereco_rua = 'r. Lamenha Lins, 2178 ap. 34' where aluno_id = 	573	;
update alunos set aluno_endereco_rua = 'r. Pe Anchieta, 1142' where aluno_id = 	574	;
update alunos set aluno_endereco_rua = 'Av. Iraí, 1200' where aluno_id = 	575	;
update alunos set aluno_endereco_rua = 'r. Dom Orione, 280' where aluno_id = 	576	;
update alunos set aluno_endereco_rua = 'R. Dr. Manoel Pedro, 670 ap. 202' where aluno_id = 	577	;
update alunos set aluno_endereco_rua = 'R. Dr. Manoel Pedro, 670 ap. 202' where aluno_id = 	578	;
update alunos set aluno_endereco_rua = 'r. João Itiberê, 4' where aluno_id = 	579	;
update alunos set aluno_endereco_rua = 'R. Pasteur, 260 ap. 1202' where aluno_id = 	581	;
update alunos set aluno_endereco_rua = 'R. Barão de Guaraúna, 95' where aluno_id = 	582	;
update alunos set aluno_endereco_rua = 'R. Barão de Guaraúna, 95' where aluno_id = 	583	;
update alunos set aluno_endereco_rua = 'R. Dr. Muricy, 439 ap. 83' where aluno_id = 	584	;
update alunos set aluno_endereco_rua = 'R. Purus, 34' where aluno_id = 	585	;
update alunos set aluno_endereco_rua = 'R. Cristiano Strobel. Conj. Amazonas 200 casa10' where aluno_id = 	586	;
update alunos set aluno_endereco_rua = 'Pça Itália, 21' where aluno_id = 	587	;
update alunos set aluno_endereco_rua = 'Augusto Severo, 200' where aluno_id = 	588	;
update alunos set aluno_endereco_rua = 'Augusto Severo, 200' where aluno_id = 	589	;
update alunos set aluno_endereco_rua = 'r. Domingas V. Zaninelli, 42' where aluno_id = 	591	;
update alunos set aluno_endereco_rua = 'Av. Alferes Poli, 209/501' where aluno_id = 	593	;
update alunos set aluno_endereco_rua = 'R. Bruno Filgueira, 2100 ap. 133' where aluno_id = 	594	;
update alunos set aluno_endereco_rua = 'R. Comendador Macedo, 260 ap. 13' where aluno_id = 	595	;
update alunos set aluno_endereco_rua = 'R. Padre Anchieta, 1576 ap. 151' where aluno_id = 	596	;
update alunos set aluno_endereco_rua = 'Jaime Rodrigues da Rocha, 736' where aluno_id = 	597	;
update alunos set aluno_endereco_rua = 'R. Jaime Rodrigues da Rocha, 736' where aluno_id = 	598	;
update alunos set aluno_endereco_rua = 'R. Jaime Rodrigues da Rocha, 736' where aluno_id = 	599	;
update alunos set aluno_endereco_rua = 'R. Jaime Rodrigues da Rocha, 736' where aluno_id = 	600	;
update alunos set aluno_endereco_rua = 'Av. Visconde de Guarapuava, 3630' where aluno_id = 	601	;
update alunos set aluno_endereco_rua = 'R. Araujo Porto Alegre, 13' where aluno_id = 	602	;
update alunos set aluno_endereco_rua = 'R. Araujo Porto Alegre, 13' where aluno_id = 	603	;
update alunos set aluno_endereco_rua = 'R. Araujo Porto Alegre, 13' where aluno_id = 	604	;
update alunos set aluno_endereco_rua = 'Av. Rep. Argentina, 789 ap. 26C' where aluno_id = 	606	;
update alunos set aluno_endereco_rua = 'D. Pedrosa, 104 ap. 601/602' where aluno_id = 	607	;
update alunos set aluno_endereco_rua = 'Av. João Gualberto, 1538 13º andar' where aluno_id = 	608	;
update alunos set aluno_endereco_rua = 'Av. João Gualberto, 1538' where aluno_id = 	609	;
update alunos set aluno_endereco_rua = 'Av. João Gualberto, 1538 13º andar' where aluno_id = 	611	;
update alunos set aluno_endereco_rua = 'R. Profº Zildo Manoel da Cruz, 30' where aluno_id = 	612	;
update alunos set aluno_endereco_rua = 'R. Dr. Pedrosa, 264 ap. 802 A' where aluno_id = 	613	;
update alunos set aluno_endereco_rua = 'R. Domingos Vigo Zanineli, 43' where aluno_id = 	614	;
update alunos set aluno_endereco_rua = 'R. José Fiori, 102' where aluno_id = 	615	;
update alunos set aluno_endereco_rua = 'R. José Augusto dos Santos, 60' where aluno_id = 	617	;
update alunos set aluno_endereco_rua = 'R. José Augusto dos Santos, 60' where aluno_id = 	618	;
update alunos set aluno_endereco_rua = 'R. Bruno Filgueira, 2100 ap. 133' where aluno_id = 	619	;
update alunos set aluno_endereco_rua = 'r. Pinheiro Guimarais, 1313' where aluno_id = 	621	;
update alunos set aluno_endereco_rua = 'R. Pinheiro Guimaraes, 1313' where aluno_id = 	622	;
update alunos set aluno_endereco_rua = 'R. Dep. Joaquim José Pedrosa, 78' where aluno_id = 	623	;
update alunos set aluno_endereco_rua = 'R. Nunes Machado, 1154' where aluno_id = 	624	;
update alunos set aluno_endereco_rua = 'R. Marechal Malet, 760' where aluno_id = 	625	;
update alunos set aluno_endereco_rua = 'Av. João Gualberto, 1134' where aluno_id = 	626	;
update alunos set aluno_endereco_rua = 'R. Cel. Joaquim Inácio Taborda Ribas, 684 ap. 91' where aluno_id = 	627	;
update alunos set aluno_endereco_rua = 'r. Profº Raul Pinheiro Machado, 280' where aluno_id = 	628	;
update alunos set aluno_endereco_rua = 'R. Cristiano Strobel, 200 cs 10' where aluno_id = 	629	;
update alunos set aluno_endereco_rua = 'r. Mato Grosso, 200' where aluno_id = 	630	;
update alunos set aluno_endereco_rua = 'r. Mato Grosso, 200' where aluno_id = 	631	;
update alunos set aluno_endereco_rua = 'R. Matim Afonso, 642' where aluno_id = 	632	;
update alunos set aluno_endereco_rua = 'R. Denezau A Jesus, 152' where aluno_id = 	633	;
update alunos set aluno_endereco_rua = 'R. Bruno Filgueira, 2100 ap. 131' where aluno_id = 	635	;
update alunos set aluno_endereco_rua = 'r. Nunes  Machado, 257' where aluno_id = 	636	;
update alunos set aluno_endereco_rua = 'R. Bento Viana, 540' where aluno_id = 	637	;
update alunos set aluno_endereco_rua = 'r. Bento Viana, 540' where aluno_id = 	638	;
update alunos set aluno_endereco_rua = 'R. Fernando Simas, 1859' where aluno_id = 	639	;
update alunos set aluno_endereco_rua = 'R. Mato Grosso, 200' where aluno_id = 	641	;
update alunos set aluno_endereco_rua = 'r. Clóvis Bevilaqua, 8' where aluno_id = 	642	;
update alunos set aluno_endereco_rua = 'R. Dr. Raul Carneiro Filho, 229' where aluno_id = 	643	;
update alunos set aluno_endereco_rua = 'R. Tem. Coronel João Antonio Ramalho, 123' where aluno_id = 	644	;
update alunos set aluno_endereco_rua = 'R. Pasteur, 225- ap. 92' where aluno_id = 	645	;
update alunos set aluno_endereco_rua = 'Av. João Gualberto, 1538' where aluno_id = 	646	;
update alunos set aluno_endereco_rua = 'Rodovia do Café Km 7,5' where aluno_id = 	647	;
update alunos set aluno_endereco_rua = 'Trav. Francisco Rafael Greca, 98 ap. 21' where aluno_id = 	648	;
update alunos set aluno_endereco_rua = 'R. 24 de Maio, 1450 ap. 06' where aluno_id = 	649	;
update alunos set aluno_endereco_rua = 'R. Eng. Niepce da Silva, 250 ap. 161 Bl. D' where aluno_id = 	650	;
update alunos set aluno_endereco_rua = 'R. Primo Lourenço Tosin, 115' where aluno_id = 	652	;
update alunos set aluno_endereco_rua = 'Omélia Monteiro Soares, 1358' where aluno_id = 	653	;
update alunos set aluno_endereco_rua = 'R. Comendador Franco, 5555' where aluno_id = 	654	;
update alunos set aluno_endereco_rua = 'R. João Dranka, 100' where aluno_id = 	655	;
update alunos set aluno_endereco_rua = 'R. 24 de Maio, 1450 ap. 06' where aluno_id = 	656	;
update alunos set aluno_endereco_rua = 'R. D. Pedro I, 389 ap. 5' where aluno_id = 	657	;
update alunos set aluno_endereco_rua = 'r. Capitão Caetano Munhoz, 70/14' where aluno_id = 	658	;
update alunos set aluno_endereco_rua = 'R. Eng. Arthur Bettes, 1533 ap. 601' where aluno_id = 	659	;
update alunos set aluno_endereco_rua = '' where aluno_id = 	660	;
update alunos set aluno_endereco_rua = 'R. Domingos Vigo Zaninelli, 72' where aluno_id = 	661	;
update alunos set aluno_endereco_rua = 'R. José Serrato, 1031 Bl. 04 ap. 102' where aluno_id = 	662	;
update alunos set aluno_endereco_rua = 'R. Lamenha Lins, 260 ap. 701' where aluno_id = 	664	;
update alunos set aluno_endereco_rua = 'Omélio Monteiro Soares, 1358' where aluno_id = 	665	;
update alunos set aluno_endereco_rua = 'Omélio Monteiro Soares, 1358' where aluno_id = 	666	;
update alunos set aluno_endereco_rua = 'R. Pasteur,300 ap. 172' where aluno_id = 	667	;
update alunos set aluno_endereco_rua = 'Av. Argentina, 85' where aluno_id = 	669	;
update alunos set aluno_endereco_rua = 'R. Bom Jesus de Iguape, 3721' where aluno_id = 	670	;
update alunos set aluno_endereco_rua = 'R. Otávio Francisco Dias, 805' where aluno_id = 	671	;
update alunos set aluno_endereco_rua = 'R. Pasteur, 225 ap. 92' where aluno_id = 	672	;
update alunos set aluno_endereco_rua = 'R. Coronel Duládio, 1080' where aluno_id = 	673	;
update alunos set aluno_endereco_rua = 'R. Pedro Demeterco, 640' where aluno_id = 	674	;
update alunos set aluno_endereco_rua = 'R. Primo Lourenço Tosin, 115' where aluno_id = 	676	;
update alunos set aluno_endereco_rua = 'R. Dr. Raul Caneiro Filho, 229 ap. 303' where aluno_id = 	677	;
update alunos set aluno_endereco_rua = 'R. Capitão Souza Franco, 833 ap. 142' where aluno_id = 	678	;
update alunos set aluno_endereco_rua = 'R. Mendelson Bartoldi, 57' where aluno_id = 	679	;
update alunos set aluno_endereco_rua = 'Av. República Argentina, 1690' where aluno_id = 	680	;
update alunos set aluno_endereco_rua = 'Omélio Monteiro Soares, 1358' where aluno_id = 	681	;
update alunos set aluno_endereco_rua = 'R. Adelino Leal Nunes, 108' where aluno_id = 	682	;
update alunos set aluno_endereco_rua = 'r. Profº José Nogueira do Santo' where aluno_id = 	683	;
update alunos set aluno_endereco_rua = 'Buenos Aires, 681 ap. 801' where aluno_id = 	684	;
update alunos set aluno_endereco_rua = 'R. Afonso Oswaldo Y., 75' where aluno_id = 	685	;
update alunos set aluno_endereco_rua = 'R. Rio Grande do Sul, 199' where aluno_id = 	686	;
update alunos set aluno_endereco_rua = 'R. Rio Grande do Sul, 199' where aluno_id = 	687	;
update alunos set aluno_endereco_rua = 'Travessa: José Surugi, 125' where aluno_id = 	689	;
update alunos set aluno_endereco_rua = 'R. Colombia, 431' where aluno_id = 	690	;
update alunos set aluno_endereco_rua = 'Lamenha Lins, 1110' where aluno_id = 	691	;
update alunos set aluno_endereco_rua = 'R. Eng. Niepce da Silva, 422 ap. 41' where aluno_id = 	692	;
update alunos set aluno_endereco_rua = 'R. Vicente Machado, 479' where aluno_id = 	693	;
update alunos set aluno_endereco_rua = '' where aluno_id = 	694	;
update alunos set aluno_endereco_rua = 'R. Pedro Gusso, 485 ap. 22 Bl. 3' where aluno_id = 	695	;
update alunos set aluno_endereco_rua = 'Waldemar Kosh, 2010' where aluno_id = 	696	;
update alunos set aluno_endereco_rua = 'R. Waldemar Kosh, 2010' where aluno_id = 	697	;
update alunos set aluno_endereco_rua = 'Av. Winston Churchill, 2030 ap. 4' where aluno_id = 	699	;
update alunos set aluno_endereco_rua = 'r. João Ferreira Leite, 281' where aluno_id = 	700	;
update alunos set aluno_endereco_rua = 'Olz. Motta, 1289 ap. 72' where aluno_id = 	702	;
update alunos set aluno_endereco_rua = 'R. Maurício Caillet, 300 ap. 32' where aluno_id = 	703	;
update alunos set aluno_endereco_rua = 'R. Alm gonçalves, 2763' where aluno_id = 	704	;
update alunos set aluno_endereco_rua = 'R. Alm. Gonçalves, 2763' where aluno_id = 	705	;
update alunos set aluno_endereco_rua = 'Av. Winston Chuechill, 2030 ap. 4' where aluno_id = 	707	;
update alunos set aluno_endereco_rua = 'R. Homero Camargo de Oliveira, 330' where aluno_id = 	708	;
update alunos set aluno_endereco_rua = 'Marechal Deodoro, 503 ap. 1502' where aluno_id = 	709	;
update alunos set aluno_endereco_rua = 'Omilio Monteiro Soares, 1358' where aluno_id = 	710	;
update alunos set aluno_endereco_rua = 'R. Mendelson Bartoldi, 57' where aluno_id = 	712	;
update alunos set aluno_endereco_rua = 'R. Coronel Bulcidio, 1383' where aluno_id = 	713	;
update alunos set aluno_endereco_rua = 'R. João Ferreira Leite, 281' where aluno_id = 	714	;
update alunos set aluno_endereco_rua = 'R. João Ferreira Leite, 281' where aluno_id = 	715	;
update alunos set aluno_endereco_rua = 'R. Dom Orione, 280' where aluno_id = 	716	;
update alunos set aluno_endereco_rua = 'R. Mendelson, 57' where aluno_id = 	717	;
update alunos set aluno_endereco_rua = 'Martim Afonso, 642' where aluno_id = 	718	;
update alunos set aluno_endereco_rua = 'R. Martim Afonso, 642' where aluno_id = 	719	;
update alunos set aluno_endereco_rua = 'R. Emílio de Menezes, 20 ap. 11' where aluno_id = 	720	;
update alunos set aluno_endereco_rua = 'Dr. Pedrosa, 134 ap. 32' where aluno_id = 	722	;
update alunos set aluno_endereco_rua = 'R. Coronel Dulcídio, 1080' where aluno_id = 	723	;
update alunos set aluno_endereco_rua = 'R. Coronel Dulcídio, 1080' where aluno_id = 	724	;
update alunos set aluno_endereco_rua = 'R. Dr. Pedrosa, 104 ap. 806' where aluno_id = 	725	;
update alunos set aluno_endereco_rua = 'Ernesto Wheigt, 411 Bl. 101' where aluno_id = 	726	;
update alunos set aluno_endereco_rua = 'R. João Ferreira Leite, 281' where aluno_id = 	728	;
update alunos set aluno_endereco_rua = 'R. Martins Leme, 1031 fundos' where aluno_id = 	730	;
update alunos set aluno_endereco_rua = 'Eça de Queirós, 113' where aluno_id = 	731	;
update alunos set aluno_endereco_rua = 'hildebrando de Araújo, 992' where aluno_id = 	732	;
update alunos set aluno_endereco_rua = 'Travessa Lange, 145 ap. 1602' where aluno_id = 	734	;
update alunos set aluno_endereco_rua = 'r. Mateus Leme, 1031 fundos' where aluno_id = 	735	;
update alunos set aluno_endereco_rua = 'Av. Sete de Setembro, 5407 ap. 31' where aluno_id = 	736	;
update alunos set aluno_endereco_rua = 'Travessa Lange, 145 ap. 1602' where aluno_id = 	737	;
update alunos set aluno_endereco_rua = 'Av. Sete de Setembro, 5407 ap. 31' where aluno_id = 	738	;
update alunos set aluno_endereco_rua = 'Gregório de Mattos, 300' where aluno_id = 	740	;
update alunos set aluno_endereco_rua = 'Gregório de Mattos, 300' where aluno_id = 	741	;
update alunos set aluno_endereco_rua = 'r. Emiliano Perneta, 823' where aluno_id = 	742	;
update alunos set aluno_endereco_rua = 'R. Dona Eleusina Plaisant, 737' where aluno_id = 	743	;
update alunos set aluno_endereco_rua = 'R. Marechal Deodoro, 1115 ap. 601' where aluno_id = 	744	;
update alunos set aluno_endereco_rua = 'R. Guilherme Purafrei, 2286' where aluno_id = 	745	;
update alunos set aluno_endereco_rua = 'R. Dr. Pedrosa, 78 ap. 202 - A' where aluno_id = 	747	;
update alunos set aluno_endereco_rua = 'r. Dr. Pedrosa, 78 ap. 202 - A' where aluno_id = 	748	;
update alunos set aluno_endereco_rua = 'R. Arthur Bindo, 805' where aluno_id = 	749	;
update alunos set aluno_endereco_rua = 'XV de Novembro, 2525 ap. 21' where aluno_id = 	750	;
update alunos set aluno_endereco_rua = 'XV de Novembro, 2525 ap. 21' where aluno_id = 	751	;
update alunos set aluno_endereco_rua = 'r. Joaquim Chagas Lima, 34 - Jd. Virginia III' where aluno_id = 	752	;
update alunos set aluno_endereco_rua = 'R. Mariano Torres, 468 ap. 3' where aluno_id = 	753	;
update alunos set aluno_endereco_rua = 'R. Brigadeiro Franco, 2507' where aluno_id = 	754	;
update alunos set aluno_endereco_rua = 'Gal Carneiro, 360' where aluno_id = 	755	;
update alunos set aluno_endereco_rua = 'R. Senador Alencar Guimarães, 164 ap. 4' where aluno_id = 	756	;
update alunos set aluno_endereco_rua = 'Nilo Peçanha, 166' where aluno_id = 	757	;
update alunos set aluno_endereco_rua = 'R. Contenção da Silva Pinheiro, 35' where aluno_id = 	758	;
update alunos set aluno_endereco_rua = 'r. Pretextato Taborda Ribas, 837' where aluno_id = 	759	;
update alunos set aluno_endereco_rua = 'R. Jorge Batista Crocethi, 45' where aluno_id = 	760	;
update alunos set aluno_endereco_rua = 'R. José Milleck, 145' where aluno_id = 	761	;
update alunos set aluno_endereco_rua = 'Av. Visconde de Guarapuava, 1501 ap. 41' where aluno_id = 	763	;
update alunos set aluno_endereco_rua = 'R. Maria Fatuchi, 128' where aluno_id = 	764	;
update alunos set aluno_endereco_rua = 'Trav. João Turim, 80 ap. 402' where aluno_id = 	765	;
update alunos set aluno_endereco_rua = 'Trav. João Turim, 80 ap. 402' where aluno_id = 	766	;
update alunos set aluno_endereco_rua = 'R. Coronel Dulcidio, 1256 ap. 1501' where aluno_id = 	767	;
update alunos set aluno_endereco_rua = 'Sete de Setembro, 5407 ap. 31' where aluno_id = 	768	;
update alunos set aluno_endereco_rua = 'Av. João Gualberto, 1034 ap. 401' where aluno_id = 	769	;
update alunos set aluno_endereco_rua = 'R. Sergipe, 900' where aluno_id = 	770	;
update alunos set aluno_endereco_rua = 'R. Nepomuceno da Costa, 348 ap. 21' where aluno_id = 	771	;
update alunos set aluno_endereco_rua = 'Joaquim Linhares de Lacerda, 51' where aluno_id = 	772	;
update alunos set aluno_endereco_rua = 'r. Joaquim Linhares de Lacerda, 51' where aluno_id = 	773	;
update alunos set aluno_endereco_rua = 'R. Wademar Kost, 230' where aluno_id = 	774	;
update alunos set aluno_endereco_rua = 'Av. Manoel Ribas, 8595' where aluno_id = 	775	;
update alunos set aluno_endereco_rua = 'R. Assis Figueiredo, 1057' where aluno_id = 	776	;
update alunos set aluno_endereco_rua = 'R. Assis Figueiredo, 1057' where aluno_id = 	777	;
update alunos set aluno_endereco_rua = 'r. Assis Figueiredo, 1057' where aluno_id = 	778	;
update alunos set aluno_endereco_rua = 'R. Assis Figueiredo, 1057' where aluno_id = 	779	;
update alunos set aluno_endereco_rua = 'R. Alcides Terézio de Carvalho, 87' where aluno_id = 	780	;
update alunos set aluno_endereco_rua = 'R. Alcides J. Carvalho, 87' where aluno_id = 	781	;
update alunos set aluno_endereco_rua = 'r. Alcides J. de Carvalho' where aluno_id = 	782	;
update alunos set aluno_endereco_rua = 'Av. Sete de Setembro, 1814 ap. 103' where aluno_id = 	783	;
update alunos set aluno_endereco_rua = 'Av. Sete de Setembro, 1814 ap. 103' where aluno_id = 	784	;
update alunos set aluno_endereco_rua = 'Av. Sete de Setembro, 1814 ap. 103' where aluno_id = 	786	;
update alunos set aluno_endereco_rua = 'Rua Francisco Torres, 427' where aluno_id = 	787	;
update alunos set aluno_endereco_rua = 'R. Francisco Torres, 427' where aluno_id = 	788	;
update alunos set aluno_endereco_rua = 'R. Voluntários da Pátria, 83 ap. 802' where aluno_id = 	789	;
update alunos set aluno_endereco_rua = 'R. Voluntários da Pátria, 83 ap. 802' where aluno_id = 	790	;
update alunos set aluno_endereco_rua = 'r. Bororos, 885' where aluno_id = 	791	;
update alunos set aluno_endereco_rua = 'R. Bororos, 885' where aluno_id = 	792	;
update alunos set aluno_endereco_rua = 'r. Delfim Moreira, 10' where aluno_id = 	793	;
update alunos set aluno_endereco_rua = 'r. Amintas de Barros, 637 ap. 9' where aluno_id = 	794	;
update alunos set aluno_endereco_rua = 'Av. Visconde de Guarapuava, 3315 ap. 43' where aluno_id = 	795	;
update alunos set aluno_endereco_rua = 'R. Rubens Carlos de Assumpção, 110' where aluno_id = 	796	;
update alunos set aluno_endereco_rua = 'R. Rubens Carlos de Assumpção, 110' where aluno_id = 	797	;
update alunos set aluno_endereco_rua = 'r. Bom Jesus de Iguape, 3721' where aluno_id = 	798	;
update alunos set aluno_endereco_rua = 'r. Estados Unidos, 1195' where aluno_id = 	800	;
update alunos set aluno_endereco_rua = 'R. Alferes angelo Sampaio, 315' where aluno_id = 	801	;
update alunos set aluno_endereco_rua = 'r. M. Floriano Peixoto, 7251' where aluno_id = 	802	;
update alunos set aluno_endereco_rua = 'r. Desembargador Westphalem, 466' where aluno_id = 	803	;
update alunos set aluno_endereco_rua = 'R. Conceição da Silva Pinheiro,35' where aluno_id = 	804	;
update alunos set aluno_endereco_rua = 'saldanha Marinho, 1310 ap. C' where aluno_id = 	805	;
update alunos set aluno_endereco_rua = 'Saldanha Marinho, 1310 ap. C' where aluno_id = 	806	;
update alunos set aluno_endereco_rua = 'Saldanha Marinho, 1310 ap. C' where aluno_id = 	807	;
update alunos set aluno_endereco_rua = 'Saldanha Marinho, 1310 ap. C' where aluno_id = 	808	;
update alunos set aluno_endereco_rua = 'R. Aristides Athayde, 779' where aluno_id = 	809	;
update alunos set aluno_endereco_rua = 'R. Francisco Motta Machado, 566' where aluno_id = 	810	;
update alunos set aluno_endereco_rua = 'R. Pedro Demeterco, 640' where aluno_id = 	811	;
update alunos set aluno_endereco_rua = 'Gregório de Mattos, 300' where aluno_id = 	812	;
update alunos set aluno_endereco_rua = 'R. Vereador Adeodato Volp., 485' where aluno_id = 	814	;
update alunos set aluno_endereco_rua = 'R. Pedro Demeterco, 46' where aluno_id = 	815	;
update alunos set aluno_endereco_rua = 'R. Ribeirão Claro, 258' where aluno_id = 	816	;
update alunos set aluno_endereco_rua = 'R. Des. Cesta Carvalho, 79' where aluno_id = 	817	;
update alunos set aluno_endereco_rua = 'r. Des. Costa Carvalho, 79' where aluno_id = 	818	;
update alunos set aluno_endereco_rua = 'Av. Visconde de Guarapuava, 150 ap. 4' where aluno_id = 	819	;
update alunos set aluno_endereco_rua = 'R. Profª Doracy Cesarino, 543' where aluno_id = 	820	;
update alunos set aluno_endereco_rua = 'R. Profª Doracy Cesarino, 543' where aluno_id = 	821	;
update alunos set aluno_endereco_rua = 'R. Manoel Correia de Freitas, 1101' where aluno_id = 	822	;
update alunos set aluno_endereco_rua = 'R. Buenos Aires, 630 ap. 1104' where aluno_id = 	823	;
update alunos set aluno_endereco_rua = 'r. Buenos Aires, 630 ap. 1104' where aluno_id = 	824	;
update alunos set aluno_endereco_rua = 'R. Valentindeda, 665' where aluno_id = 	825	;
update alunos set aluno_endereco_rua = 'R. Valentindeda, 665' where aluno_id = 	826	;
update alunos set aluno_endereco_rua = 'R. José D. Sobrinho, 126' where aluno_id = 	828	;
update alunos set aluno_endereco_rua = 'Mateus Leme, 3249' where aluno_id = 	829	;
update alunos set aluno_endereco_rua = 'R. Dr. Eusebio de Oliveira, 567' where aluno_id = 	830	;
update alunos set aluno_endereco_rua = 'R. Dr. Eusebio de Oliveira, 567' where aluno_id = 	831	;
update alunos set aluno_endereco_rua = 'R. Dr. Euzebio de Oliveira, 567' where aluno_id = 	832	;
update alunos set aluno_endereco_rua = 'r. Leonaldo Krassiki' where aluno_id = 	833	;
update alunos set aluno_endereco_rua = 'Imaculada Conceição, 220' where aluno_id = 	834	;
update alunos set aluno_endereco_rua = 'Av. Batel , 1505 ap. 51' where aluno_id = 	835	;
update alunos set aluno_endereco_rua = 'Capitão João Busse, 280' where aluno_id = 	836	;
update alunos set aluno_endereco_rua = 'R. Engenheiros Rebouças, 30' where aluno_id = 	838	;
update alunos set aluno_endereco_rua = 'R. Com. Antônio de M. de Barros' where aluno_id = 	839	;
update alunos set aluno_endereco_rua = 'R. Gal. Dalto Filho, 522' where aluno_id = 	840	;
update alunos set aluno_endereco_rua = 'R. Nicolau Serrato Sobrinho, 39' where aluno_id = 	841	;
update alunos set aluno_endereco_rua = 'R. Nicolau Serrato Sobrinho, 39' where aluno_id = 	842	;
update alunos set aluno_endereco_rua = 'R. Nicolau Serrato Sobrinho, 39' where aluno_id = 	843	;
update alunos set aluno_endereco_rua = 'r. Professor Francisco Zardo, 1410' where aluno_id = 	844	;
update alunos set aluno_endereco_rua = 'Av. Sete de Setembro, 4633 ap.1001' where aluno_id = 	845	;
update alunos set aluno_endereco_rua = '' where aluno_id = 	846	;
update alunos set aluno_endereco_rua = 'R. Prof. José Maurício Higgns, 1476' where aluno_id = 	848	;
update alunos set aluno_endereco_rua = 'R. Dr. Pedrosa, 104' where aluno_id = 	851	;
update alunos set aluno_endereco_rua = 'Av. 7 de Setembro, 3815  Ap. 41' where aluno_id = 	852	;
update alunos set aluno_endereco_rua = 'R. Saldanha Marinho, 1918  ap. 08' where aluno_id = 	853	;
update alunos set aluno_endereco_rua = 'R. Profª Olga Balster, 1525' where aluno_id = 	854	;
update alunos set aluno_endereco_rua = 'R. Padre Anchieta, 2690  Ap. 303' where aluno_id = 	855	;
update alunos set aluno_endereco_rua = 'R. Luiz Ronaldo Canalli, 3025/34-C' where aluno_id = 	856	;
update alunos set aluno_endereco_rua = 'R. Dr. Pedrosa, 104  Ap. 807' where aluno_id = 	857	;
update alunos set aluno_endereco_rua = 'R. Professor Assis Gonçalves, 1476  Ap. 23' where aluno_id = 	858	;
update alunos set aluno_endereco_rua = 'Av. Anita Garibaldi, 964  Ap. 904B' where aluno_id = 	859	;
update alunos set aluno_endereco_rua = 'R. Luiz Ronaldo Canalli, 3025/34-C' where aluno_id = 	860	;
update alunos set aluno_endereco_rua = 'R. Vicente Machado, 1430' where aluno_id = 	861	;
update alunos set aluno_endereco_rua = 'R. Padre José Kentenica, 179  casa 5' where aluno_id = 	862	;
update alunos set aluno_endereco_rua = 'R.Arcésio Guimarães, 448A' where aluno_id = 	863	;
update alunos set aluno_endereco_rua = 'R. Padre Ancheita, 2690' where aluno_id = 	864	;
update alunos set aluno_endereco_rua = 'R. Ana Bertha Roskamp, 761' where aluno_id = 	865	;
update alunos set aluno_endereco_rua = 'R. Padre Anchieta, 2690  Ap. 1102' where aluno_id = 	866	;
update alunos set aluno_endereco_rua = 'R. Conselheiro Laurindo, 781  Ap. 1002' where aluno_id = 	867	;
update alunos set aluno_endereco_rua = 'R. Joaquim Amaral, 693' where aluno_id = 	868	;
update alunos set aluno_endereco_rua = 'Al. Augusto Stelfelld, 1539   Ap. 501' where aluno_id = 	869	;
update alunos set aluno_endereco_rua = 'R. Miguel Abrão, 309   casa 09' where aluno_id = 	870	;
update alunos set aluno_endereco_rua = 'R. Mar. Floriano Peixoto, 6124' where aluno_id = 	872	;
update alunos set aluno_endereco_rua = 'R. José Kormann, 523' where aluno_id = 	873	;
update alunos set aluno_endereco_rua = 'R. Parintins, 303  Ap. 62' where aluno_id = 	874	;
update alunos set aluno_endereco_rua = 'R. Francisco Maravalhas, 47' where aluno_id = 	876	;
update alunos set aluno_endereco_rua = 'R. Fernando Simas, 1417' where aluno_id = 	879	;
update alunos set aluno_endereco_rua = 'R. Pe. Anchieta, 1231  Ap. 131' where aluno_id = 	880	;
update alunos set aluno_endereco_rua = 'R. Uruguai, 109     casa 3' where aluno_id = 	881	;
update alunos set aluno_endereco_rua = 'R. José Lopes dos Santos, 336' where aluno_id = 	882	;
update alunos set aluno_endereco_rua = 'R. Desembargador Motta, 3467  casa 6' where aluno_id = 	883	;
update alunos set aluno_endereco_rua = 'R. Dr. Zamenhof, 288  Ap. 31' where aluno_id = 	884	;
update alunos set aluno_endereco_rua = 'R. Paulo Gorski, 1101  casa 21' where aluno_id = 	887	;
update alunos set aluno_endereco_rua = 'Av. República Argentina, 2500  Ap. 1004' where aluno_id = 	888	;
update alunos set aluno_endereco_rua = 'R. Eça de Queiros, 1295  Ap. 31B' where aluno_id = 	889	;
update alunos set aluno_endereco_rua = 'R. Gottileb Rosenau, 276' where aluno_id = 	890	;
update alunos set aluno_endereco_rua = 'R. Nunes Machado, 422  Ap. 502' where aluno_id = 	891	;
update alunos set aluno_endereco_rua = 'R. Saldanha Marinho, 1918   Ap. 08' where aluno_id = 	892	;
update alunos set aluno_endereco_rua = 'R. João Pontoni, 98  Ap. 91' where aluno_id = 	893	;
update alunos set aluno_endereco_rua = 'R. Conselheiro Laurindo, 2635' where aluno_id = 	894	;
update alunos set aluno_endereco_rua = 'R. Petit Carneiro, 1027/143' where aluno_id = 	895	;
update alunos set aluno_endereco_rua = 'R. Rogerio de Aguilar Minetto,41' where aluno_id = 	896	;
update alunos set aluno_endereco_rua = 'R. Vicente Machado, 2678' where aluno_id = 	897	;
update alunos set aluno_endereco_rua = 'R.Adílio Ramos, 3085' where aluno_id = 	898	;
update alunos set aluno_endereco_rua = 'Av. Iguaçú, 2141  Ap. 44' where aluno_id = 	899	;
update alunos set aluno_endereco_rua = 'R. Mato Grosso, 354  Ap. 12-B' where aluno_id = 	900	;
update alunos set aluno_endereco_rua = 'R. XV de Novembro, 2535  Ap. 12' where aluno_id = 	901	;
update alunos set aluno_endereco_rua = 'R. Brigadeiro Franco, 1652   Ap. 212' where aluno_id = 	903	;
update alunos set aluno_endereco_rua = 'R. Conselheiro Laurindo, 2635' where aluno_id = 	904	;
update alunos set aluno_endereco_rua = 'Av. Silva Jardim, 2235' where aluno_id = 	905	;
update alunos set aluno_endereco_rua = 'Av. Silva Jardim, 2235' where aluno_id = 	906	;
update alunos set aluno_endereco_rua = 'R. Rodolfo Senff Jr, 477' where aluno_id = 	908	;
update alunos set aluno_endereco_rua = 'R. Paraguassú, 538  Ap. 12' where aluno_id = 	909	;
update alunos set aluno_endereco_rua = 'Alameda Julia da Costa, 1525/31' where aluno_id = 	910	;
update alunos set aluno_endereco_rua = 'Alameda Julia da Costa, 1525/31' where aluno_id = 	911	;
update alunos set aluno_endereco_rua = 'Av. Silva Jardim' where aluno_id = 	912	;
update alunos set aluno_endereco_rua = 'R. Paraguassú, 538   Ap. 12' where aluno_id = 	913	;
update alunos set aluno_endereco_rua = 'R. João Ernesto Kilian, 1358' where aluno_id = 	914	;
update alunos set aluno_endereco_rua = 'R. Dep. Heitor Alencar Furtado, 1433  Ap. 901' where aluno_id = 	915	;
update alunos set aluno_endereco_rua = 'R.Dep.  Heitor Alencar Furtado, 1433' where aluno_id = 	916	;
update alunos set aluno_endereco_rua = 'R. Palmeiras, 295  Ap. 63' where aluno_id = 	917	;
update alunos set aluno_endereco_rua = 'R. Presidente Epitácio Pessoa, 84' where aluno_id = 	918	;
update alunos set aluno_endereco_rua = 'R. Almirante Tamandaré, 1755' where aluno_id = 	919	;
update alunos set aluno_endereco_rua = 'Av. Iguaçú, 2960  Ap. 171-A' where aluno_id = 	920	;
update alunos set aluno_endereco_rua = 'Rua Pará, 1801   Ap. 54' where aluno_id = 	921	;
update alunos set aluno_endereco_rua = 'R. Santo Antonio, 555  Ap. 07-D' where aluno_id = 	922	;
update alunos set aluno_endereco_rua = 'R. Joaquim Amaral, 693' where aluno_id = 	923	;
update alunos set aluno_endereco_rua = 'R. Tibúrcio Brasil, 58   sobrado 13' where aluno_id = 	924	;
update alunos set aluno_endereco_rua = 'R. Gumercindo Mares, 150  casa 25' where aluno_id = 	925	;
update alunos set aluno_endereco_rua = 'R. Samuel Cesar, 1341' where aluno_id = 	926	;
update alunos set aluno_endereco_rua = 'Travessa Lange, 277  Ap. 2402' where aluno_id = 	927	;
update alunos set aluno_endereco_rua = 'R. Ana Bertha Roskamp, 761' where aluno_id = 	928	;
update alunos set aluno_endereco_rua = 'R. Profª. Olga Balster, 1525' where aluno_id = 	929	;
update alunos set aluno_endereco_rua = 'R. Montese, 390' where aluno_id = 	930	;
update alunos set aluno_endereco_rua = 'R. Prof. Assis Gonçalves, 1342  Ap. 31' where aluno_id = 	931	;
update alunos set aluno_endereco_rua = 'Av. Com. Franco, 5803  casa 12' where aluno_id = 	932	;
update alunos set aluno_endereco_rua = 'Av. Com. Franco, 5803   casa 12' where aluno_id = 	933	;
update alunos set aluno_endereco_rua = 'R. Nunes Machado, 481  Apto. 2102' where aluno_id = 	934	;
update alunos set aluno_endereco_rua = 'R. Piaui, 2011' where aluno_id = 	935	;
update alunos set aluno_endereco_rua = 'R. Rio Grande do Sul, 116  Apto. 124' where aluno_id = 	936	;
update alunos set aluno_endereco_rua = 'R. Rogério de Aguilar Mineto, 41' where aluno_id = 	937	;
update alunos set aluno_endereco_rua = 'R. João Pontoni, 98   Ap. 162' where aluno_id = 	938	;
update alunos set aluno_endereco_rua = 'R. Professor Dario Veloso, 110   Ap. 901 B' where aluno_id = 	939	;
update alunos set aluno_endereco_rua = 'R. Saldanha Marinho, 1918  ap. 08' where aluno_id = 	940	;
update alunos set aluno_endereco_rua = 'R. Gottileab Rosenau, 276' where aluno_id = 	941	;
update alunos set aluno_endereco_rua = 'R. Professor Assis Gonçalves, 1476   Ap. 23' where aluno_id = 	942	;
update alunos set aluno_endereco_rua = 'Av. Mal. Floriano Peixoto, 6124' where aluno_id = 	943	;
update alunos set aluno_endereco_rua = 'R. Marechal Hermes, 297   Ap. 94' where aluno_id = 	944	;
update alunos set aluno_endereco_rua = 'Av. Visconde de Guarapuava, 4177  Ap. 1602' where aluno_id = 	945	;
update alunos set aluno_endereco_rua = 'Rua Padre Anchieta, 2224' where aluno_id = 	946	;
update alunos set aluno_endereco_rua = 'Av. dos Estados, 189   Ap. 14' where aluno_id = 	947	;
update alunos set aluno_endereco_rua = 'R. Mato Grosso, 354 12-B' where aluno_id = 	948	;
update alunos set aluno_endereco_rua = 'R. Rockefeller, 783   Ap. 302' where aluno_id = 	949	;
update alunos set aluno_endereco_rua = 'R. Prof. Dario Veloso' where aluno_id = 	950	;
update alunos set aluno_endereco_rua = 'R. Padre Agostinho, 2715   Ap. 224' where aluno_id = 	951	;
update alunos set aluno_endereco_rua = 'R. Hipólito da Costa, 1556' where aluno_id = 	952	;
update alunos set aluno_endereco_rua = 'R. Emiliano Perneta, 653  Ap. 14' where aluno_id = 	953	;
update alunos set aluno_endereco_rua = 'R. Leonardo Wesolowski' where aluno_id = 	954	;
update alunos set aluno_endereco_rua = 'R. Dr. Pedrosa, 78   apto. 702 B' where aluno_id = 	955	;
update alunos set aluno_endereco_rua = 'Av. Silva Jardim, 1887   Apto. 1301' where aluno_id = 	956	;
update alunos set aluno_endereco_rua = 'R. Pretextato Taborda Jr. 1220' where aluno_id = 	957	;
update alunos set aluno_endereco_rua = 'R. Estevão Baião, 90' where aluno_id = 	958	;
update alunos set aluno_endereco_rua = 'R. Estevão Baião, 90' where aluno_id = 	959	;
update alunos set aluno_endereco_rua = 'R. C. Tem. Maris de Barros, 880' where aluno_id = 	960	;
update alunos set aluno_endereco_rua = 'Rua Piauí, 2011' where aluno_id = 	961	;
update alunos set aluno_endereco_rua = 'Av. Pres. Get´lio Vargas, 4482' where aluno_id = 	962	;
update alunos set aluno_endereco_rua = 'R. Prof. Dario veloso, 110  Ap. 901 B' where aluno_id = 	963	;
update alunos set aluno_endereco_rua = 'R. Heitor Baggio Vidal, 826' where aluno_id = 	964	;
update alunos set aluno_endereco_rua = 'R. Des. Motta, 3467   casa 6' where aluno_id = 	965	;
update alunos set aluno_endereco_rua = 'R. Gumercindo Mares, 150  casa 25' where aluno_id = 	967	;
update alunos set aluno_endereco_rua = 'R. Orlando Luiz Lamarca, 357  Casa' where aluno_id = 	968	;
update alunos set aluno_endereco_rua = 'R. Nunes Machado, 471  Ap. 502' where aluno_id = 	969	;
update alunos set aluno_endereco_rua = 'R. José Kormann, 523' where aluno_id = 	970	;
update alunos set aluno_endereco_rua = 'R. Mato Grosso, 354  Ap. 12 B' where aluno_id = 	971	;
update alunos set aluno_endereco_rua = 'Al. Carlos de carvalho, 1041  ap. 702' where aluno_id = 	972	;
update alunos set aluno_endereco_rua = 'R. Tamboara' where aluno_id = 	973	;
update alunos set aluno_endereco_rua = 'R. Eça de Queiroz, 1083   Ap. 205' where aluno_id = 	974	;
update alunos set aluno_endereco_rua = 'R. Cel. Alfredo Ferreira da Costa, 1300' where aluno_id = 	975	;
update alunos set aluno_endereco_rua = 'R. Atilio Bório, 1828' where aluno_id = 	976	;
update alunos set aluno_endereco_rua = 'R. José Loureiro, 646   Ap. 95' where aluno_id = 	977	;
update alunos set aluno_endereco_rua = '' where aluno_id = 	978	;
update alunos set aluno_endereco_rua = 'R. Augsto Stelfelld, 1539   apto. 501' where aluno_id = 	979	;
update alunos set aluno_endereco_rua = 'R. Visconde de Nacar, 1200   Ap. 56' where aluno_id = 	980	;
update alunos set aluno_endereco_rua = 'R. das Nações Unidas, 1038' where aluno_id = 	981	;
update alunos set aluno_endereco_rua = 'R. Lamenha Lins, 530 - 51B' where aluno_id = 	982	;
update alunos set aluno_endereco_rua = 'R. Anne Frank, 1434' where aluno_id = 	983	;
update alunos set aluno_endereco_rua = 'R. Alberto de Oliveira, 460' where aluno_id = 	984	;
update alunos set aluno_endereco_rua = 'R. Canadá, 809' where aluno_id = 	985	;
update alunos set aluno_endereco_rua = 'R. Marechal Hermes, 297   Ap. 94' where aluno_id = 	986	;
update alunos set aluno_endereco_rua = 'R. Tem. Mais de Barros, 880' where aluno_id = 	987	;
update alunos set aluno_endereco_rua = 'R. Adílio Ramos, 3085' where aluno_id = 	988	;
update alunos set aluno_endereco_rua = 'R. Rodolfo Senff Jr, 477' where aluno_id = 	989	;
update alunos set aluno_endereco_rua = '' where aluno_id = 	990	;
update alunos set aluno_endereco_rua = 'Al. Julia da Costa 1135' where aluno_id = 	995	;
update alunos set aluno_endereco_rua = 'Visconde de Guarapuava 3630' where aluno_id = 	996	;
update alunos set aluno_endereco_rua = '' where aluno_id = 	997	;
update alunos set aluno_endereco_rua = 'Oliveira viana, 3608' where aluno_id = 	998	;
update alunos set aluno_endereco_rua = 'R. Baltazar L' where aluno_id = 	1001	;
update alunos set aluno_endereco_rua = 'Rua Mons.Manoel Vicente, 842  Apto 303' where aluno_id = 	1002	;
update alunos set aluno_endereco_rua = 'Rua Angelo Trevisan, 530 casa 4' where aluno_id = 	1004	;
update alunos set aluno_endereco_rua = 'Tr. Rafael Francisco Greca, 98 ap 21' where aluno_id = 	1005	;
update alunos set aluno_endereco_rua = 'R. Nunes Machado, 481 apt. 2102' where aluno_id = 	1006	;
update alunos set aluno_endereco_rua = '' where aluno_id = 	1007	;
update alunos set aluno_endereco_rua = 'R. Gumercindo Mares 150 casa 25' where aluno_id = 	1008	;
update alunos set aluno_endereco_rua = 'Rua Cap. Caetano Munhoz, 25 casa 1' where aluno_id = 	1010	;
update alunos set aluno_endereco_rua = '' where aluno_id = 	1011	;
update alunos set aluno_endereco_rua = 'R. Nunes Machado, 2938' where aluno_id = 	1012	;
update alunos set aluno_endereco_rua = 'R. Alexandre de Gusmao, 896' where aluno_id = 	1013	;
update alunos set aluno_endereco_rua = 'Rua Nilo Peçanha, 2415' where aluno_id = 	1014	;
update alunos set aluno_endereco_rua = 'Rua Jacarezinho, 480' where aluno_id = 	1015	;
update alunos set aluno_endereco_rua = 'Rua Jacarezinho, 480' where aluno_id = 	1016	;
update alunos set aluno_endereco_rua = 'Magdalena Chagas Lima 631 c02' where aluno_id = 	1017	;
update alunos set aluno_endereco_rua = 'R. Saldanha Marinho, 1918 ap 08' where aluno_id = 	1019	;
update alunos set aluno_endereco_rua = '' where aluno_id = 	1020	;
update alunos set aluno_endereco_rua = 'R. Carenio Scorzato 568 sob 2' where aluno_id = 	1021	;
update alunos set aluno_endereco_rua = 'Martim Afonso 1918 ap. 111' where aluno_id = 	1022	;
update alunos set aluno_endereco_rua = 'Rua anne Frank 1434' where aluno_id = 	1024	;
update alunos set aluno_endereco_rua = 'João Bonat 430 apt 703' where aluno_id = 	1025	;
update alunos set aluno_endereco_rua = 'R. José Zaramella 160 sob. 02' where aluno_id = 	1026	;
update alunos set aluno_endereco_rua = 'Av. Manoel Ribas 707 ap 161 B' where aluno_id = 	1027	;
update alunos set aluno_endereco_rua = 'Rua Eng. Arthur Bettes, 42 Ap 142' where aluno_id = 	1028	;
update alunos set aluno_endereco_rua = 'Rua Buenos Aires 590 ap 301' where aluno_id = 	1029	;
update alunos set aluno_endereco_rua = 'K. Ivo Leão,477 ap 21 C' where aluno_id = 	1033	;
update alunos set aluno_endereco_rua = 'dom Pedro I, 667' where aluno_id = 	1034	;
update alunos set aluno_endereco_rua = 'R. Baltazar Carrasco dos Reis' where aluno_id = 	1036	;
update alunos set aluno_endereco_rua = 'Rua Padre Julio Saavedra,843 casa 03' where aluno_id = 	1038	;
update alunos set aluno_endereco_rua = 'Francisco Alves Guimarâes, 100 ap 81' where aluno_id = 	1039	;
update alunos set aluno_endereco_rua = 'Rua Luis França, 782  casa 3' where aluno_id = 	1041	;
update alunos set aluno_endereco_rua = 'Rua Jose Tomasi 931' where aluno_id = 	1043	;
update alunos set aluno_endereco_rua = 'Av. Pres. Getúlio Vargas, 4482' where aluno_id = 	1046	;
update alunos set aluno_endereco_rua = 'Dr. Pedrosa 104 ap. 107' where aluno_id = 	1048	;
update alunos set aluno_endereco_rua = 'R: José Francisco Dalledone, 237  Sob. 15' where aluno_id = 	1049	;
update alunos set aluno_endereco_rua = 'R. Manoel L. Lacerda, 84 ap 1201 B' where aluno_id = 	1050	;
update alunos set aluno_endereco_rua = 'Vitório do Amaral Cattani, 61 Cs 03' where aluno_id = 	1051	;
update alunos set aluno_endereco_rua = 'Vitório do Amaral Cattani, 61  casa 3' where aluno_id = 	1052	;
update alunos set aluno_endereco_rua = 'Rua Guilherme Pugsley, 1188 ap 112' where aluno_id = 	1053	;
update alunos set aluno_endereco_rua = 'Atilio Bório, 80 ap 102' where aluno_id = 	1054	;
update alunos set aluno_endereco_rua = 'Atilio Bório, 80 ap. 102' where aluno_id = 	1055	;
update alunos set aluno_endereco_rua = 'R. Benjamin Constant, 257  Ap.22' where aluno_id = 	1060	;
update alunos set aluno_endereco_rua = 'R: Cel. Alfredo Ferreira da Costa, 289' where aluno_id = 	1061	;
update alunos set aluno_endereco_rua = 'R: Comendador Correia Jr, 383 A' where aluno_id = 	1062	;
update alunos set aluno_endereco_rua = 'R: Prefeito Angelo Ferrario Lopes, 2552  Apto 201' where aluno_id = 	1063	;
update alunos set aluno_endereco_rua = 'R: Antonio Lago, 420  Sob. 05' where aluno_id = 	1064	;
update alunos set aluno_endereco_rua = 'R: Visconde Rio Branco, 1800' where aluno_id = 	1065	;
update alunos set aluno_endereco_rua = 'R: Cel.Alfredo Ferreira da Costa, 289' where aluno_id = 	1066	;
update alunos set aluno_endereco_rua = 'R: Buenos Aires, 658  Apto 702' where aluno_id = 	1067	;
update alunos set aluno_endereco_rua = 'R: Capitão Tenente Maris de Barros,780' where aluno_id = 	1068	;
update alunos set aluno_endereco_rua = 'R: Buenos Aires, 658  Apto 702' where aluno_id = 	1069	;
update alunos set aluno_endereco_rua = 'R: Urbano Lopes, 60  Apto 1602' where aluno_id = 	1070	;
update alunos set aluno_endereco_rua = 'R: Urbano Lopes, 60  Apto 1602' where aluno_id = 	1071	;
update alunos set aluno_endereco_rua = 'Rua José Tomas, 352' where aluno_id = 	1072	;
update alunos set aluno_endereco_rua = 'Rua Saldanha Marinho, 847  Apto 41' where aluno_id = 	1073	;
update alunos set aluno_endereco_rua = 'R: Padre Júlio Saavedra, 846  Sob.03' where aluno_id = 	1074	;
update alunos set aluno_endereco_rua = 'R: Padre Júlio Saavedra, 843  Sob. 06' where aluno_id = 	1075	;
update alunos set aluno_endereco_rua = 'R: Engenheiro Teodoro Sampaio, 131 - 2' where aluno_id = 	1076	;
update alunos set aluno_endereco_rua = 'R: Ver. Washington Mansur, 84  Apto 53' where aluno_id = 	1077	;
update alunos set aluno_endereco_rua = 'R. Raposo Tavares, 1084' where aluno_id = 	1078	;
update alunos set aluno_endereco_rua = 'R. Ver.Washington Mansur, 84  apto 53' where aluno_id = 	1079	;
update alunos set aluno_endereco_rua = 'Rua Belem, 322  Apto 301' where aluno_id = 	1080	;
update alunos set aluno_endereco_rua = 'R: Lima Barreto, 1396' where aluno_id = 	1081	;
update alunos set aluno_endereco_rua = 'R. Padre Julio Saavedra, 789' where aluno_id = 	1082	;
update alunos set aluno_endereco_rua = 'R: Claudio Manoel da Costa, 266' where aluno_id = 	1083	;
update alunos set aluno_endereco_rua = 'R: Claudio Manoel da Costa, 266' where aluno_id = 	1084	;
update alunos set aluno_endereco_rua = 'Comendador Correia Jr., 383 A' where aluno_id = 	1085	;
update alunos set aluno_endereco_rua = 'R: Clóvis Bevilaqua, 28  Apto 23' where aluno_id = 	1086	;
update alunos set aluno_endereco_rua = 'R: Engenheiro Teodoro Sampaio, 131-2' where aluno_id = 	1087	;
update alunos set aluno_endereco_rua = 'Av. Iguaçu, 2713' where aluno_id = 	1088	;
update alunos set aluno_endereco_rua = 'R: Visconde do Rio Branco, 42  Apto 603' where aluno_id = 	1089	;
update alunos set aluno_endereco_rua = 'Rua Bruno Filgueira, 1936' where aluno_id = 	1090	;
update alunos set aluno_endereco_rua = 'R: Carlos Dietzsch, 1301' where aluno_id = 	1091	;
update alunos set aluno_endereco_rua = 'Av. Iguaçú, 2713  Apto 604' where aluno_id = 	1094	;
update alunos set aluno_endereco_rua = 'R: Angelo Trevisan, 530  casa 4' where aluno_id = 	1095	;
update alunos set aluno_endereco_rua = 'Rua Belem, 322  Apto 301' where aluno_id = 	1096	;
update alunos set aluno_endereco_rua = 'R: José Francisco Dalledone, 237' where aluno_id = 	1097	;
update alunos set aluno_endereco_rua = 'R: Toaldo Túlio, 158  Apto 4' where aluno_id = 	1100	;
update alunos set aluno_endereco_rua = 'R: Toaldo Túlio, 158  Apto 4' where aluno_id = 	1101	;
update alunos set aluno_endereco_rua = 'R: Visconde do Rio Branco, 42  Apto 603' where aluno_id = 	1103	;
update alunos set aluno_endereco_rua = 'R: José Zaramella, 160  Sob. 02' where aluno_id = 	1104	;
update alunos set aluno_endereco_rua = 'R. Simão Brante, 23  Casa 2' where aluno_id = 	1107	;
update alunos set aluno_endereco_rua = 'R: Rafael Arcanjo Machado, 159  Sob.2' where aluno_id = 	1108	;
update alunos set aluno_endereco_rua = 'R: Visconde de Nacar, 1.200  Apto 56' where aluno_id = 	1113	;
update alunos set aluno_endereco_rua = 'Rua João de Lara, 27 -D' where aluno_id = 	1114	;
update alunos set aluno_endereco_rua = 'Rua Leôncio Correia, 223' where aluno_id = 	1117	;
update alunos set aluno_endereco_rua = 'Av.Iguaçú, 2960  Apto. 171 A' where aluno_id = 	1118	;
update alunos set aluno_endereco_rua = 'R: Curupaitis, 1570' where aluno_id = 	1119	;
update alunos set aluno_endereco_rua = 'Rua Curupaitis, 1570' where aluno_id = 	1120	;
update alunos set aluno_endereco_rua = 'R: Catarina Gabardo, 1530' where aluno_id = 	1121	;
update alunos set aluno_endereco_rua = 'R: José Benedito Cotollengo, 810' where aluno_id = 	1122	;
update alunos set aluno_endereco_rua = 'R: Capitão Tenente Maris de Barros, 780' where aluno_id = 	1123	;
update alunos set aluno_endereco_rua = 'Rua Marechal Hermes,872, AP 6B' where aluno_id = 	1124	;
update alunos set aluno_endereco_rua = 'Rua Desembargador Isaías Bevilaqua, 889' where aluno_id = 	1126	;
update alunos set aluno_endereco_rua = 'Rua Hipólito da Costa, 319' where aluno_id = 	1130	;
update alunos set aluno_endereco_rua = 'Rua Jacob Bertinato, 193' where aluno_id = 	1131	;
update alunos set aluno_endereco_rua = 'Rua Jacob Bertinato, 193' where aluno_id = 	1132	;
update alunos set aluno_endereco_rua = 'Rua Terra Boa, 414' where aluno_id = 	1133	;
update alunos set aluno_endereco_rua = 'Zeferino Anibal Ferrarini, s/n' where aluno_id = 	1135	;
update alunos set aluno_endereco_rua = 'Rua Vecente Gerona, 550   980' where aluno_id = 	1137	;
update alunos set aluno_endereco_rua = 'Rua Guararapes, 1391, AP 502' where aluno_id = 	1138	;
update alunos set aluno_endereco_rua = 'R. Getúlio Vargas, 681' where aluno_id = 	1139	;
update alunos set aluno_endereco_rua = 'Rua Aracaju, 1029, sob.01' where aluno_id = 	1141	;
update alunos set aluno_endereco_rua = 'R. Ver. Washington Mansur, 84, AP 53' where aluno_id = 	1142	;
update alunos set aluno_endereco_rua = 'Rua Francisco Scremin, 287' where aluno_id = 	1143	;
update alunos set aluno_endereco_rua = 'Rua Francisco Scremin, 287' where aluno_id = 	1144	;
update alunos set aluno_endereco_rua = 'Rua Padre Julio Saavedra, 843, Sob. 06' where aluno_id = 	1145	;
update alunos set aluno_endereco_rua = 'Rua Visconde do Serro Frio, 161, AP 801' where aluno_id = 	1146	;
update alunos set aluno_endereco_rua = 'Rua Professor Macedo Filho,4 23' where aluno_id = 	1147	;
update alunos set aluno_endereco_rua = 'Rua Prefeito Ângelo Lopes, 2552, AP 201' where aluno_id = 	1149	;
update alunos set aluno_endereco_rua = 'Rua Frei Gaspar Madre Deus, 391, AP 406, BL 2' where aluno_id = 	1150	;
update alunos set aluno_endereco_rua = 'Rua José Cadilhe, 871' where aluno_id = 	1151	;
update alunos set aluno_endereco_rua = 'Rua José Cadilhe, 871' where aluno_id = 	1152	;
