-- MySQL Script generated by MySQL Workbench
-- Sat Oct 12 15:58:34 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema junshin
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema junshin
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `junshin` ;
USE `junshin` ;

-- -----------------------------------------------------
-- Table `junshin`.`tipos_documento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `junshin`.`tipos_documento` (
  `tipo_documento_id` INT NOT NULL AUTO_INCREMENT,
  `tipo_documento_descricao` VARCHAR(45) NOT NULL,
  `ativo` TINYINT(1) NOT NULL DEFAULT 1,
  `userid_insert` VARCHAR(45) NOT NULL,
  `datahora_insert` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`tipo_documento_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `junshin`.`niveis_conhecimento_japones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `junshin`.`niveis_conhecimento_japones` (
  `nivel_conhecimento_japones_id` INT NOT NULL AUTO_INCREMENT,
  `nivel_conhecimento_japones_descricao` VARCHAR(45) NOT NULL,
  `ativo` TINYINT(1) NOT NULL DEFAULT 1,
  `userid_insert` VARCHAR(45) NOT NULL,
  `datahora_insert` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`nivel_conhecimento_japones_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `junshin`.`niveis_escolaridade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `junshin`.`niveis_escolaridade` (
  `nivel_escolaridade_id` INT NOT NULL AUTO_INCREMENT,
  `nivel_escolaridade_descricao` VARCHAR(45) NOT NULL,
  `ativo` TINYINT(1) NOT NULL DEFAULT 1,
  `userid_insert` VARCHAR(45) NOT NULL,
  `datahora_insert` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`nivel_escolaridade_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `junshin`.`alunos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `junshin`.`alunos` (
  `aluno_id` INT NOT NULL AUTO_INCREMENT,
  `aluno_nome` VARCHAR(100) NOT NULL,
  `aluno_codigo` VARCHAR(45) NOT NULL,
  `aluno_foto` VARCHAR(45) NULL,
  `aluno_data_nascimento` DATE NOT NULL,
  `aluno_local_nascimento` VARCHAR(45) NOT NULL,
  `tipo_documento_id` INT NOT NULL,
  `aluno_documento` VARCHAR(45) NOT NULL,
  `aluno_sexo` CHAR(1) NOT NULL,
  `nivel_escolaridade_id` INT NOT NULL,
  `aluno_endereco_rua` VARCHAR(45) NOT NULL,
  `aluno_endereco_numero` VARCHAR(10) NOT NULL,
  `aluno_endereco_complemento` VARCHAR(10) NULL,
  `aluno_endereco_bairro` VARCHAR(45) NOT NULL,
  `aluno_endereco_cep` VARCHAR(10) NOT NULL,
  `aluno_endereco_cidade` VARCHAR(45) NOT NULL,
  `aluno_endereco_estado` VARCHAR(2) NOT NULL,
  `aluno_telefone_fixo` VARCHAR(20) NULL,
  `aluno_telefone_celular` VARCHAR(20) NULL,
  `aluno_telefone_recado` VARCHAR(20) NULL,
  `aluno_religiao` VARCHAR(45) NULL,
  `aluno_email` VARCHAR(45) NULL,
  `aluno_observacao` VARCHAR(255) NULL,
  `aluno_quantidade_irmaos` INT NULL,
  `aluno_ordem_nascimento` INT NULL,
  `aluno_ordem_geracao` INT NULL,
  `nivel_conhecimento_japones_id` INT NOT NULL,
  `aluno_vacinado` TINYINT(1) NOT NULL DEFAULT 0,
  `aluno_vacinado_observacao` VARCHAR(255) NULL,
  `ativo` TINYINT(1) NOT NULL DEFAULT 1,
  `userid_insert` VARCHAR(45) NOT NULL,
  `datahora_insert` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`aluno_id`),
  INDEX `fk_alunos_tipos_documento_idx` (`tipo_documento_id` ASC),
  INDEX `fk_alunos_niveis_conhecimento_japones_idx` (`nivel_conhecimento_japones_id` ASC),
  INDEX `fk_alunos_niveis_escolaridade_aluno_idx` (`nivel_escolaridade_id` ASC),
  CONSTRAINT `fk_alunos_tipos_documento`
    FOREIGN KEY (`tipo_documento_id`)
    REFERENCES `junshin`.`tipos_documento` (`tipo_documento_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_alunos_niveis_conhecimento_japones`
    FOREIGN KEY (`nivel_conhecimento_japones_id`)
    REFERENCES `junshin`.`niveis_conhecimento_japones` (`nivel_conhecimento_japones_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_alunos_niveis_escolaridade_aluno`
    FOREIGN KEY (`nivel_escolaridade_id`)
    REFERENCES `junshin`.`niveis_escolaridade` (`nivel_escolaridade_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `junshin`.`tipos_turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `junshin`.`tipos_turma` (
  `tipo_turma_id` INT NOT NULL AUTO_INCREMENT,
  `tipo_turma_descricao` VARCHAR(45) NOT NULL,
  `ativo` TINYINT(1) NOT NULL DEFAULT 1,
  `userid_insert` VARCHAR(45) NOT NULL,
  `datahora_insert` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`tipo_turma_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `junshin`.`turnos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `junshin`.`turnos` (
  `turno_id` INT NOT NULL AUTO_INCREMENT,
  `turno_descricao` VARCHAR(45) NOT NULL,
  `ativo` TINYINT(1) NOT NULL DEFAULT 1,
  `userid_insert` VARCHAR(45) NOT NULL,
  `datahora` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`turno_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `junshin`.`tipos_frequencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `junshin`.`tipos_frequencia` (
  `tipo_frequencia_id` INT NOT NULL AUTO_INCREMENT,
  `tipos_frequencia_descricao` VARCHAR(45) NOT NULL,
  `ativo` TINYINT(1) NOT NULL DEFAULT 1,
  `userid_insert` VARCHAR(45) NOT NULL,
  `datahora_insert` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`tipo_frequencia_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `junshin`.`turmas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `junshin`.`turmas` (
  `turma_id` INT NOT NULL AUTO_INCREMENT,
  `tipo_turma_id` INT NOT NULL,
  `turno_id` INT NOT NULL,
  `tipo_frequencia_id` INT NOT NULL,
  `turma_descricao` VARCHAR(45) NOT NULL,
  `turma_observacao` VARCHAR(255) NULL,
  `ativo` TINYINT(1) NOT NULL DEFAULT 1,
  `userid_insert` VARCHAR(45) NOT NULL,
  `datahora_insert` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`turma_id`),
  INDEX `fk_turmas_tipos_turma_idx` (`tipo_turma_id` ASC),
  INDEX `fk_turmas_turnos_idx` (`turno_id` ASC),
  INDEX `fk_turmas_tipos_frequencia_idx` (`tipo_frequencia_id` ASC),
  CONSTRAINT `fk_turmas_tipos_turma`
    FOREIGN KEY (`tipo_turma_id`)
    REFERENCES `junshin`.`tipos_turma` (`tipo_turma_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_turmas_turnos`
    FOREIGN KEY (`turno_id`)
    REFERENCES `junshin`.`turnos` (`turno_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_turmas_tipos_frequencia`
    FOREIGN KEY (`tipo_frequencia_id`)
    REFERENCES `junshin`.`tipos_frequencia` (`tipo_frequencia_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `junshin`.`moradores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `junshin`.`moradores` (
  `morador_id` INT NOT NULL AUTO_INCREMENT,
  `aluno_id` INT NOT NULL,
  `morador_nome` VARCHAR(45) NOT NULL,
  `morador_vinculo` VARCHAR(45) NOT NULL,
  `morador_data_nascimento` DATE NULL,
  `morador_sexo` CHAR(1) NOT NULL,
  `ativo` TINYINT(1) NOT NULL DEFAULT 1,
  `userid_insert` VARCHAR(45) NOT NULL,
  `datahora_insert` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`morador_id`),
  INDEX `fk_moradores_alunos_idx` (`aluno_id` ASC),
  CONSTRAINT `fk_moradores_alunos`
    FOREIGN KEY (`aluno_id`)
    REFERENCES `junshin`.`alunos` (`aluno_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `junshin`.`historico_instituicoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `junshin`.`historico_instituicoes` (
  `historico_instituicao_id` INT NOT NULL AUTO_INCREMENT,
  `aluno_id` INT NOT NULL,
  `historico_instituicao_nome` VARCHAR(45) NOT NULL,
  `historico_instituicao_ano` INT NULL,
  `historico_instituicao_serie` VARCHAR(45) NULL,
  `ativo` TINYINT(1) NOT NULL DEFAULT 1,
  `userid_insert` VARCHAR(45) NOT NULL,
  `datahora_insert` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`historico_instituicao_id`),
  INDEX `fk_historico_instituicoes_alunos_idx` (`aluno_id` ASC),
  CONSTRAINT `fk_historico_instituicoes_alunos`
    FOREIGN KEY (`aluno_id`)
    REFERENCES `junshin`.`alunos` (`aluno_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `junshin`.`mensalidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `junshin`.`mensalidades` (
  `mensalidade_id` INT NOT NULL AUTO_INCREMENT,
  `matricula_id` INT NOT NULL,
  `mensalidade_valor` DECIMAL(10,2) NOT NULL,
  `mensalidade_data_ini` TIMESTAMP NOT NULL,
  `mensalidade_data_fim` TIMESTAMP NULL,
  `ativo` TINYINT(1) NOT NULL DEFAULT 1,
  `userid_insert` VARCHAR(45) NOT NULL,
  `datahora_insert` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`mensalidade_id`),
  INDEX `fk_mensalidades_matriculas_idx` (`matricula_id` ASC),
  CONSTRAINT `fk_mensalidades_matriculas`
    FOREIGN KEY (`matricula_id`)
    REFERENCES `junshin`.`matriculas` (`matricula_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `junshin`.`matriculas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `junshin`.`matriculas` (
  `matricula_id` INT NOT NULL AUTO_INCREMENT,
  `turma_id` INT NOT NULL,
  `aluno_id` INT NOT NULL,
  `matricula_data_ini` DATE NOT NULL,
  `matricula_data_fim` DATE NOT NULL,
  `ativo` TINYINT(1) NOT NULL DEFAULT 1,
  `userid_insert` VARCHAR(45) NOT NULL,
  `datahora_insert` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `mensalidades_mensalidade_id` INT NOT NULL,
  PRIMARY KEY (`matricula_id`),
  INDEX `fk_matriculas_turmas_idx` (`turma_id` ASC),
  INDEX `fk_matriculas_alunos_idx` (`aluno_id` ASC),
  INDEX `fk_matriculas_mensalidades1_idx` (`mensalidades_mensalidade_id` ASC),
  CONSTRAINT `fk_matriculas_turmas`
    FOREIGN KEY (`turma_id`)
    REFERENCES `junshin`.`turmas` (`turma_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_matriculas_alunos`
    FOREIGN KEY (`aluno_id`)
    REFERENCES `junshin`.`alunos` (`aluno_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_matriculas_mensalidades1`
    FOREIGN KEY (`mensalidades_mensalidade_id`)
    REFERENCES `junshin`.`mensalidades` (`mensalidade_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `junshin`.`tipos_movimentacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `junshin`.`tipos_movimentacao` (
  `tipo_movimentacao_id` INT NOT NULL AUTO_INCREMENT,
  `tipo_movimentacao` TINYINT(1) NOT NULL COMMENT '0 - Entrada\n1 - Saída',
  `tipo_movimentacao_descricao` VARCHAR(45) NOT NULL,
  `ativo` TINYINT(1) NOT NULL DEFAULT 1,
  `userid_insert` VARCHAR(45) NOT NULL,
  `datahora_insert` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`tipo_movimentacao_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `junshin`.`movimentacoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `junshin`.`movimentacoes` (
  `movimentacao_id` INT NOT NULL AUTO_INCREMENT,
  `tipo_movimentacao_id` INT NOT NULL,
  `movimentacao_data` DATE NOT NULL,
  `movimentacao_valor` DECIMAL(10,2) NOT NULL,
  `movimentacao_observacao` VARCHAR(255) NULL,
  `ativo` TINYINT(1) NOT NULL DEFAULT 1,
  `userid_insert` VARCHAR(45) NOT NULL,
  `datahora_insert` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`movimentacao_id`),
  INDEX `fk_movimentacao_tipos_movimentacao_idx` (`tipo_movimentacao_id` ASC),
  CONSTRAINT `fk_movimentacao_tipos_movimentacao`
    FOREIGN KEY (`tipo_movimentacao_id`)
    REFERENCES `junshin`.`tipos_movimentacao` (`tipo_movimentacao_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `junshin`.`tipos_responsavel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `junshin`.`tipos_responsavel` (
  `tipo_responsavel_id` INT NOT NULL AUTO_INCREMENT,
  `tipo_responsavel_descricao` VARCHAR(45) NOT NULL,
  `ativo` TINYINT(1) NOT NULL DEFAULT 1,
  `userid_insert` VARCHAR(45) NOT NULL,
  `datahora_insert` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`tipo_responsavel_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `junshin`.`responsaveis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `junshin`.`responsaveis` (
  `responsavel_id` INT NOT NULL AUTO_INCREMENT,
  `tipo_responsavel_id` INT NOT NULL,
  `aluno_id` INT NOT NULL,
  `responsavel_nome` VARCHAR(100) NULL,
  `responsavel_firma` VARCHAR(45) NULL,
  `responsavel_telefone_firma` VARCHAR(20) NULL,
  `responsavel_ramal_firma` VARCHAR(10) NULL,
  `responsavel_celular` VARCHAR(20) NULL,
  `responsavel_email` VARCHAR(45) NULL,
  `responsavel_nascionalidade` VARCHAR(45) NULL,
  `responsavel_data_nascimento` DATE NULL,
  `responsavel_ordem_geracao` INT NULL,
  `responsavel_religiao` VARCHAR(45) NULL,
  `responsavel_escolaridade_id` INT NULL,
  `ativo` TINYINT(1) NOT NULL DEFAULT 1,
  `user_insert` VARCHAR(45) NOT NULL,
  `datahora_insert` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`responsavel_id`),
  INDEX `fk_responsaveis_tipos_responsavel_idx` (`tipo_responsavel_id` ASC),
  INDEX `fk_responsaveis_alunos_idx` (`aluno_id` ASC),
  CONSTRAINT `fk_responsaveis_tipos_responsavel`
    FOREIGN KEY (`tipo_responsavel_id`)
    REFERENCES `junshin`.`tipos_responsavel` (`tipo_responsavel_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_responsaveis_alunos`
    FOREIGN KEY (`aluno_id`)
    REFERENCES `junshin`.`alunos` (`aluno_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `junshin`.`pagadores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `junshin`.`pagadores` (
  `pagador_id` INT NOT NULL AUTO_INCREMENT,
  `responsavel_id` INT NOT NULL,
  `pagador_cpf` VARCHAR(45) NOT NULL,
  `pagador_rua` VARCHAR(45) NOT NULL,
  `pagador_numero` VARCHAR(10) NOT NULL,
  `pagador_complemento` VARCHAR(10) NULL,
  `pagador_bairro` VARCHAR(45) NOT NULL,
  `pagador_cep` VARCHAR(10) NOT NULL,
  `pagador_cidade` VARCHAR(45) NOT NULL,
  `pagador_estado` VARCHAR(2) NOT NULL,
  `pagador_percentual` INT NOT NULL,
  `pagador_data_ini` DATE NOT NULL,
  `pagador_data_fim` DATE NULL,
  `ativo` TINYINT(1) NOT NULL DEFAULT 1,
  `userid_insert` VARCHAR(45) NOT NULL,
  `datahora_insert` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`pagador_id`),
  INDEX `fk_pagadores_responsaveis_idx` (`responsavel_id` ASC),
  CONSTRAINT `fk_pagadores_responsaveis`
    FOREIGN KEY (`responsavel_id`)
    REFERENCES `junshin`.`responsaveis` (`responsavel_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `junshin`.`boletos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `junshin`.`boletos` (
  `boleto_id` VARCHAR(45) NOT NULL,
  `pagador_id` INT NOT NULL,
  `boleto_valor` DECIMAL(10,2) NOT NULL,
  `boleto_vencimento` DATE NOT NULL,
  `boleto_observacao` VARCHAR(255) NULL,
  `boleto_pago` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '0 - Não pago\n1 - Pago\n2 - Pago parcialmente',
  `ativo` TINYINT(1) NOT NULL DEFAULT 1,
  `userid_insert` VARCHAR(45) NOT NULL,
  `datahora_insert` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`boleto_id`),
  INDEX `fk_boletos_pagadores_idx` (`pagador_id` ASC),
  CONSTRAINT `fk_boletos_pagadores`
    FOREIGN KEY (`pagador_id`)
    REFERENCES `junshin`.`pagadores` (`pagador_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Table `junshin`.`perfis`
-- -----------------------------------------------------
CREATE TABLE `perfis` (
  `perfil_id` int(11) NOT NULL AUTO_INCREMENT,
  `perfil_descricao` varchar(45) NOT NULL,
  `ativo` tinyint(1) NOT NULL,
  `userid_insert` varchar(45) NOT NULL,
  `datahora_insert` timestamp NOT NULL,
  PRIMARY KEY (`perfil_id`)
) ENGINE=InnoDB
-- -----------------------------------------------------
-- Table `junshin`.`users_por_perfis`
-- -----------------------------------------------------
CREATE TABLE `users_por_perfis` (
  `users_por_perfil_id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) NOT NULL,
  `perfil_id` int(11) NOT NULL,
  `ativo` tinyint(1) NOT NULL DEFAULT '1',
  `userid_insert` varchar(45) NOT NULL,
  `datahora_insert` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`users_por_perfil_id`),
  KEY `users_por_perfis_perfis_idx` (`perfil_id`),
  CONSTRAINT `users_por_perfis_perfis` FOREIGN KEY (`perfil_id`) REFERENCES `perfis` (`perfil_id`)
) ENGINE=InnoDB