insert into tipos_movimentacao (tipo_movimentacao_id,tipo_movimentacao,tipo_movimentacao_descricao,ativo,userid_insert,datahora_insert) values (1,1,'Mochila',1,"Administrador",sysdate());
insert into tipos_movimentacao (tipo_movimentacao_id,tipo_movimentacao,tipo_movimentacao_descricao,ativo,userid_insert,datahora_insert) values (2,1,'Mensalidade',1,"Administrador",sysdate());
insert into tipos_movimentacao (tipo_movimentacao_id,tipo_movimentacao,tipo_movimentacao_descricao,ativo,userid_insert,datahora_insert) values (3,1,'Acampamento',1,"Administrador",sysdate());
insert into tipos_movimentacao (tipo_movimentacao_id,tipo_movimentacao,tipo_movimentacao_descricao,ativo,userid_insert,datahora_insert) values (4,1,'Livros/pré',1,"Administrador",sysdate());
insert into tipos_movimentacao (tipo_movimentacao_id,tipo_movimentacao,tipo_movimentacao_descricao,ativo,userid_insert,datahora_insert) values (5,1,'Aluguel de Imóveis',1,"Administrador",sysdate());
insert into tipos_movimentacao (tipo_movimentacao_id,tipo_movimentacao,tipo_movimentacao_descricao,ativo,userid_insert,datahora_insert) values (7,1,'Taxa diversas',1,"Administrador",sysdate());
insert into tipos_movimentacao (tipo_movimentacao_id,tipo_movimentacao,tipo_movimentacao_descricao,ativo,userid_insert,datahora_insert) values (8,1,'Associação das Mães',1,"Administrador",sysdate());
insert into tipos_movimentacao (tipo_movimentacao_id,tipo_movimentacao,tipo_movimentacao_descricao,ativo,userid_insert,datahora_insert) values (9,1,'Xerox',1,"Administrador",sysdate());
insert into tipos_movimentacao (tipo_movimentacao_id,tipo_movimentacao,tipo_movimentacao_descricao,ativo,userid_insert,datahora_insert) values (10,1,'Apostilas/pré',1,"Administrador",sysdate());
insert into tipos_movimentacao (tipo_movimentacao_id,tipo_movimentacao,tipo_movimentacao_descricao,ativo,userid_insert,datahora_insert) values (11,1,'Cadernos',1,"Administrador",sysdate());
insert into tipos_movimentacao (tipo_movimentacao_id,tipo_movimentacao,tipo_movimentacao_descricao,ativo,userid_insert,datahora_insert) values (12,1,'Uniformes',1,"Administrador",sysdate());
insert into tipos_movimentacao (tipo_movimentacao_id,tipo_movimentacao,tipo_movimentacao_descricao,ativo,userid_insert,datahora_insert) values (13,1,'Contribuições',1,"Administrador",sysdate());
insert into tipos_movimentacao (tipo_movimentacao_id,tipo_movimentacao,tipo_movimentacao_descricao,ativo,userid_insert,datahora_insert) values (14,1,'Outros',1,"Administrador",sysdate());
insert into tipos_movimentacao (tipo_movimentacao_id,tipo_movimentacao,tipo_movimentacao_descricao,ativo,userid_insert,datahora_insert) values (15,1,'Taxa material-Pré',1,"Administrador",sysdate());
insert into tipos_movimentacao (tipo_movimentacao_id,tipo_movimentacao,tipo_movimentacao_descricao,ativo,userid_insert,datahora_insert) values (18,1,'Taxa de material -curso',1,"Administrador",sysdate());
insert into tipos_movimentacao (tipo_movimentacao_id,tipo_movimentacao,tipo_movimentacao_descricao,ativo,userid_insert,datahora_insert) values (19,1,'Nenhum',1,"Administrador",sysdate());
insert into tipos_movimentacao (tipo_movimentacao_id,tipo_movimentacao,tipo_movimentacao_descricao,ativo,userid_insert,datahora_insert) values (20,1,'Juros mensalidade',1,"Administrador",sysdate());
insert into tipos_movimentacao (tipo_movimentacao_id,tipo_movimentacao,tipo_movimentacao_descricao,ativo,userid_insert,datahora_insert) values (21,1,'Juros',1,"Administrador",sysdate());
insert into tipos_movimentacao (tipo_movimentacao_id,tipo_movimentacao,tipo_movimentacao_descricao,ativo,userid_insert,datahora_insert) values (26,1,'Saldo-Cx',1,"Administrador",sysdate());
insert into tipos_movimentacao (tipo_movimentacao_id,tipo_movimentacao,tipo_movimentacao_descricao,ativo,userid_insert,datahora_insert) values (27,1,'Doação',1,"Administrador",sysdate());
insert into tipos_movimentacao (tipo_movimentacao_id,tipo_movimentacao,tipo_movimentacao_descricao,ativo,userid_insert,datahora_insert) values (28,1,'matrícula',1,"Administrador",sysdate());
insert into tipos_movimentacao (tipo_movimentacao_id,tipo_movimentacao,tipo_movimentacao_descricao,ativo,userid_insert,datahora_insert) values (29,1,'Reposição Cheque devolvido',1,"Administrador",sysdate());
insert into tipos_movimentacao (tipo_movimentacao_id,tipo_movimentacao,tipo_movimentacao_descricao,ativo,userid_insert,datahora_insert) values (30,1,'Restituição - Assoc.Franc.BJ',1,"Administrador",sysdate());
insert into tipos_movimentacao (tipo_movimentacao_id,tipo_movimentacao,tipo_movimentacao_descricao,ativo,userid_insert,datahora_insert) values (31,1,'notas',1,"Administrador",sysdate());
insert into tipos_movimentacao (tipo_movimentacao_id,tipo_movimentacao,tipo_movimentacao_descricao,ativo,userid_insert,datahora_insert) values (32,1,'festa',1,"Administrador",sysdate());
insert into tipos_movimentacao (tipo_movimentacao_id,tipo_movimentacao,tipo_movimentacao_descricao,ativo,userid_insert,datahora_insert) values (33,1,'bazar',1,"Administrador",sysdate());
insert into tipos_movimentacao (tipo_movimentacao_id,tipo_movimentacao,tipo_movimentacao_descricao,ativo,userid_insert,datahora_insert) values (34,1,'undokai',1,"Administrador",sysdate());
insert into tipos_movimentacao (tipo_movimentacao_id,tipo_movimentacao,tipo_movimentacao_descricao,ativo,userid_insert,datahora_insert) values (35,1,'almoco',1,"Administrador",sysdate());
insert into tipos_movimentacao (tipo_movimentacao_id,tipo_movimentacao,tipo_movimentacao_descricao,ativo,userid_insert,datahora_insert) values (36,1,'apostila curso',1,"Administrador",sysdate());
insert into tipos_movimentacao (tipo_movimentacao_id,tipo_movimentacao,tipo_movimentacao_descricao,ativo,userid_insert,datahora_insert) values (37,0,'Acampamento',1,"Administrador",sysdate());
insert into tipos_movimentacao (tipo_movimentacao_id,tipo_movimentacao,tipo_movimentacao_descricao,ativo,userid_insert,datahora_insert) values (38,0,'Água',1,"Administrador",sysdate());
insert into tipos_movimentacao (tipo_movimentacao_id,tipo_movimentacao,tipo_movimentacao_descricao,ativo,userid_insert,datahora_insert) values (39,0,'Aluguel',1,"Administrador",sysdate());
insert into tipos_movimentacao (tipo_movimentacao_id,tipo_movimentacao,tipo_movimentacao_descricao,ativo,userid_insert,datahora_insert) values (40,0,'Associação das mães',1,"Administrador",sysdate());
insert into tipos_movimentacao (tipo_movimentacao_id,tipo_movimentacao,tipo_movimentacao_descricao,ativo,userid_insert,datahora_insert) values (41,0,'Banco Cart. Cheque',1,"Administrador",sysdate());
insert into tipos_movimentacao (tipo_movimentacao_id,tipo_movimentacao,tipo_movimentacao_descricao,ativo,userid_insert,datahora_insert) values (42,0,'Carro-Licenciamento',1,"Administrador",sysdate());
insert into tipos_movimentacao (tipo_movimentacao_id,tipo_movimentacao,tipo_movimentacao_descricao,ativo,userid_insert,datahora_insert) values (43,0,'Carro-manutenção',1,"Administrador",sysdate());
insert into tipos_movimentacao (tipo_movimentacao_id,tipo_movimentacao,tipo_movimentacao_descricao,ativo,userid_insert,datahora_insert) values (44,0,'Carro-Seguro',1,"Administrador",sysdate());
insert into tipos_movimentacao (tipo_movimentacao_id,tipo_movimentacao,tipo_movimentacao_descricao,ativo,userid_insert,datahora_insert) values (45,0,'Cheque devolvido',1,"Administrador",sysdate());
insert into tipos_movimentacao (tipo_movimentacao_id,tipo_movimentacao,tipo_movimentacao_descricao,ativo,userid_insert,datahora_insert) values (46,0,'Combustível',1,"Administrador",sysdate());
insert into tipos_movimentacao (tipo_movimentacao_id,tipo_movimentacao,tipo_movimentacao_descricao,ativo,userid_insert,datahora_insert) values (47,0,'Computador-despesas',1,"Administrador",sysdate());
insert into tipos_movimentacao (tipo_movimentacao_id,tipo_movimentacao,tipo_movimentacao_descricao,ativo,userid_insert,datahora_insert) values (48,0,'Construção-mão de obra',1,"Administrador",sysdate());
insert into tipos_movimentacao (tipo_movimentacao_id,tipo_movimentacao,tipo_movimentacao_descricao,ativo,userid_insert,datahora_insert) values (49,0,'Construção-Material',1,"Administrador",sysdate());
insert into tipos_movimentacao (tipo_movimentacao_id,tipo_movimentacao,tipo_movimentacao_descricao,ativo,userid_insert,datahora_insert) values (50,0,'Contador',1,"Administrador",sysdate());
insert into tipos_movimentacao (tipo_movimentacao_id,tipo_movimentacao,tipo_movimentacao_descricao,ativo,userid_insert,datahora_insert) values (51,0,'Contrato Sharp',1,"Administrador",sysdate());
insert into tipos_movimentacao (tipo_movimentacao_id,tipo_movimentacao,tipo_movimentacao_descricao,ativo,userid_insert,datahora_insert) values (52,0,'Correio Postal',1,"Administrador",sysdate());
insert into tipos_movimentacao (tipo_movimentacao_id,tipo_movimentacao,tipo_movimentacao_descricao,ativo,userid_insert,datahora_insert) values (53,0,'CPMF',1,"Administrador",sysdate());
insert into tipos_movimentacao (tipo_movimentacao_id,tipo_movimentacao,tipo_movimentacao_descricao,ativo,userid_insert,datahora_insert) values (54,0,'Curso-Professor',1,"Administrador",sysdate());
insert into tipos_movimentacao (tipo_movimentacao_id,tipo_movimentacao,tipo_movimentacao_descricao,ativo,userid_insert,datahora_insert) values (55,0,'Devolução',1,"Administrador",sysdate());
insert into tipos_movimentacao (tipo_movimentacao_id,tipo_movimentacao,tipo_movimentacao_descricao,ativo,userid_insert,datahora_insert) values (56,0,'Diversos',1,"Administrador",sysdate());
insert into tipos_movimentacao (tipo_movimentacao_id,tipo_movimentacao,tipo_movimentacao_descricao,ativo,userid_insert,datahora_insert) values (57,0,'Doação',1,"Administrador",sysdate());
insert into tipos_movimentacao (tipo_movimentacao_id,tipo_movimentacao,tipo_movimentacao_descricao,ativo,userid_insert,datahora_insert) values (58,0,'Encargos',1,"Administrador",sysdate());
insert into tipos_movimentacao (tipo_movimentacao_id,tipo_movimentacao,tipo_movimentacao_descricao,ativo,userid_insert,datahora_insert) values (59,0,'Equipamento',1,"Administrador",sysdate());
insert into tipos_movimentacao (tipo_movimentacao_id,tipo_movimentacao,tipo_movimentacao_descricao,ativo,userid_insert,datahora_insert) values (60,0,'estacionamento - estar',1,"Administrador",sysdate());
insert into tipos_movimentacao (tipo_movimentacao_id,tipo_movimentacao,tipo_movimentacao_descricao,ativo,userid_insert,datahora_insert) values (61,0,'Excursão-Curso',1,"Administrador",sysdate());
insert into tipos_movimentacao (tipo_movimentacao_id,tipo_movimentacao,tipo_movimentacao_descricao,ativo,userid_insert,datahora_insert) values (62,0,'Gás',1,"Administrador",sysdate());
insert into tipos_movimentacao (tipo_movimentacao_id,tipo_movimentacao,tipo_movimentacao_descricao,ativo,userid_insert,datahora_insert) values (63,0,'Imóvel-Despesas',1,"Administrador",sysdate());
insert into tipos_movimentacao (tipo_movimentacao_id,tipo_movimentacao,tipo_movimentacao_descricao,ativo,userid_insert,datahora_insert) values (64,0,'ingles pré',1,"Administrador",sysdate());
insert into tipos_movimentacao (tipo_movimentacao_id,tipo_movimentacao,tipo_movimentacao_descricao,ativo,userid_insert,datahora_insert) values (65,0,'Integral-alimentação',1,"Administrador",sysdate());
insert into tipos_movimentacao (tipo_movimentacao_id,tipo_movimentacao,tipo_movimentacao_descricao,ativo,userid_insert,datahora_insert) values (66,0,'Integral-material',2,"Administrador",sysdate());
insert into tipos_movimentacao (tipo_movimentacao_id,tipo_movimentacao,tipo_movimentacao_descricao,ativo,userid_insert,datahora_insert) values (67,0,'IPTU',3,"Administrador",sysdate());
insert into tipos_movimentacao (tipo_movimentacao_id,tipo_movimentacao,tipo_movimentacao_descricao,ativo,userid_insert,datahora_insert) values (68,0,'lanche prof',4,"Administrador",sysdate());
insert into tipos_movimentacao (tipo_movimentacao_id,tipo_movimentacao,tipo_movimentacao_descricao,ativo,userid_insert,datahora_insert) values (69,0,'Li vro-Pré',5,"Administrador",sysdate());
insert into tipos_movimentacao (tipo_movimentacao_id,tipo_movimentacao,tipo_movimentacao_descricao,ativo,userid_insert,datahora_insert) values (70,0,'Livro-Pré-Acervo',6,"Administrador",sysdate());
insert into tipos_movimentacao (tipo_movimentacao_id,tipo_movimentacao,tipo_movimentacao_descricao,ativo,userid_insert,datahora_insert) values (71,0,'Livro/Pré',7,"Administrador",sysdate());
insert into tipos_movimentacao (tipo_movimentacao_id,tipo_movimentacao,tipo_movimentacao_descricao,ativo,userid_insert,datahora_insert) values (72,0,'Luz',8,"Administrador",sysdate());
insert into tipos_movimentacao (tipo_movimentacao_id,tipo_movimentacao,tipo_movimentacao_descricao,ativo,userid_insert,datahora_insert) values (73,0,'Manutenção',9,"Administrador",sysdate());
insert into tipos_movimentacao (tipo_movimentacao_id,tipo_movimentacao,tipo_movimentacao_descricao,ativo,userid_insert,datahora_insert) values (74,0,'manutenção paisagem',10,"Administrador",sysdate());
insert into tipos_movimentacao (tipo_movimentacao_id,tipo_movimentacao,tipo_movimentacao_descricao,ativo,userid_insert,datahora_insert) values (75,0,'manutenção-carro',11,"Administrador",sysdate());
insert into tipos_movimentacao (tipo_movimentacao_id,tipo_movimentacao,tipo_movimentacao_descricao,ativo,userid_insert,datahora_insert) values (76,0,'Manutenção-equipamento',12,"Administrador",sysdate());
insert into tipos_movimentacao (tipo_movimentacao_id,tipo_movimentacao,tipo_movimentacao_descricao,ativo,userid_insert,datahora_insert) values (77,0,'manutenção-mào de obra',13,"Administrador",sysdate());
insert into tipos_movimentacao (tipo_movimentacao_id,tipo_movimentacao,tipo_movimentacao_descricao,ativo,userid_insert,datahora_insert) values (78,0,'Manutenção-material',14,"Administrador",sysdate());
insert into tipos_movimentacao (tipo_movimentacao_id,tipo_movimentacao,tipo_movimentacao_descricao,ativo,userid_insert,datahora_insert) values (79,0,'Material-cozinha',15,"Administrador",sysdate());
insert into tipos_movimentacao (tipo_movimentacao_id,tipo_movimentacao,tipo_movimentacao_descricao,ativo,userid_insert,datahora_insert) values (80,0,'Material-Curso',16,"Administrador",sysdate());
insert into tipos_movimentacao (tipo_movimentacao_id,tipo_movimentacao,tipo_movimentacao_descricao,ativo,userid_insert,datahora_insert) values (81,0,'Material-Escritório',17,"Administrador",sysdate());
insert into tipos_movimentacao (tipo_movimentacao_id,tipo_movimentacao,tipo_movimentacao_descricao,ativo,userid_insert,datahora_insert) values (82,0,'Material-Limpeza',18,"Administrador",sysdate());
insert into tipos_movimentacao (tipo_movimentacao_id,tipo_movimentacao,tipo_movimentacao_descricao,ativo,userid_insert,datahora_insert) values (83,0,'Material-Pré',19,"Administrador",sysdate());
insert into tipos_movimentacao (tipo_movimentacao_id,tipo_movimentacao,tipo_movimentacao_descricao,ativo,userid_insert,datahora_insert) values (84,0,'Missões',20,"Administrador",sysdate());
insert into tipos_movimentacao (tipo_movimentacao_id,tipo_movimentacao,tipo_movimentacao_descricao,ativo,userid_insert,datahora_insert) values (85,0,'Mochila',21,"Administrador",sysdate());
insert into tipos_movimentacao (tipo_movimentacao_id,tipo_movimentacao,tipo_movimentacao_descricao,ativo,userid_insert,datahora_insert) values (86,0,'Móveis',22,"Administrador",sysdate());
insert into tipos_movimentacao (tipo_movimentacao_id,tipo_movimentacao,tipo_movimentacao_descricao,ativo,userid_insert,datahora_insert) values (87,0,'Nenhum',23,"Administrador",sysdate());
insert into tipos_movimentacao (tipo_movimentacao_id,tipo_movimentacao,tipo_movimentacao_descricao,ativo,userid_insert,datahora_insert) values (88,0,'Outros',24,"Administrador",sysdate());
insert into tipos_movimentacao (tipo_movimentacao_id,tipo_movimentacao,tipo_movimentacao_descricao,ativo,userid_insert,datahora_insert) values (89,0,'Pré Informática',25,"Administrador",sysdate());
insert into tipos_movimentacao (tipo_movimentacao_id,tipo_movimentacao,tipo_movimentacao_descricao,ativo,userid_insert,datahora_insert) values (90,0,'Publicidade e Propaganda',26,"Administrador",sysdate());
insert into tipos_movimentacao (tipo_movimentacao_id,tipo_movimentacao,tipo_movimentacao_descricao,ativo,userid_insert,datahora_insert) values (91,0,'Ryogae',27,"Administrador",sysdate());
insert into tipos_movimentacao (tipo_movimentacao_id,tipo_movimentacao,tipo_movimentacao_descricao,ativo,userid_insert,datahora_insert) values (92,0,'ryoushuu',28,"Administrador",sysdate());
insert into tipos_movimentacao (tipo_movimentacao_id,tipo_movimentacao,tipo_movimentacao_descricao,ativo,userid_insert,datahora_insert) values (93,0,'Salário',29,"Administrador",sysdate());
insert into tipos_movimentacao (tipo_movimentacao_id,tipo_movimentacao,tipo_movimentacao_descricao,ativo,userid_insert,datahora_insert) values (94,0,'Saúde',30,"Administrador",sysdate());
insert into tipos_movimentacao (tipo_movimentacao_id,tipo_movimentacao,tipo_movimentacao_descricao,ativo,userid_insert,datahora_insert) values (95,0,'sensei',31,"Administrador",sysdate());
insert into tipos_movimentacao (tipo_movimentacao_id,tipo_movimentacao,tipo_movimentacao_descricao,ativo,userid_insert,datahora_insert) values (96,0,'Taxa Manutenção',32,"Administrador",sysdate());
insert into tipos_movimentacao (tipo_movimentacao_id,tipo_movimentacao,tipo_movimentacao_descricao,ativo,userid_insert,datahora_insert) values (97,0,'Taxas diversas',33,"Administrador",sysdate());
insert into tipos_movimentacao (tipo_movimentacao_id,tipo_movimentacao,tipo_movimentacao_descricao,ativo,userid_insert,datahora_insert) values (98,0,'teatro aluguel',34,"Administrador",sysdate());
insert into tipos_movimentacao (tipo_movimentacao_id,tipo_movimentacao,tipo_movimentacao_descricao,ativo,userid_insert,datahora_insert) values (99,0,'Telefone',35,"Administrador",sysdate());
insert into tipos_movimentacao (tipo_movimentacao_id,tipo_movimentacao,tipo_movimentacao_descricao,ativo,userid_insert,datahora_insert) values (100,0,'TV a cabo',36,"Administrador",sysdate());
insert into tipos_movimentacao (tipo_movimentacao_id,tipo_movimentacao,tipo_movimentacao_descricao,ativo,userid_insert,datahora_insert) values (101,0,'Uniforme-Curso',37,"Administrador",sysdate());
insert into tipos_movimentacao (tipo_movimentacao_id,tipo_movimentacao,tipo_movimentacao_descricao,ativo,userid_insert,datahora_insert) values (102,0,'Uniforme-Pré',38,"Administrador",sysdate());
insert into tipos_movimentacao (tipo_movimentacao_id,tipo_movimentacao,tipo_movimentacao_descricao,ativo,userid_insert,datahora_insert) values (103,0,'Vale Transporte',39,"Administrador",sysdate());
insert into tipos_movimentacao (tipo_movimentacao_id,tipo_movimentacao,tipo_movimentacao_descricao,ativo,userid_insert,datahora_insert) values (104,0,'Viagem',40,"Administrador",sysdate());
